// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh-CN'

export type Locales =
	| 'en'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 确​定
	 */
	ok: string
	/**
	 * 取​消
	 */
	cancel: string
	/**
	 * 重​试
	 */
	retry: string
	/**
	 * 加​载​中​.​.​.
	 */
	loading: string
	/**
	 * 确​认
	 */
	confirm: string
	/**
	 * 后​退
	 */
	back: string
	/**
	 * 前​进
	 */
	forward: string
	/**
	 * 刷​新
	 */
	refresh: string
	/**
	 * 停​止
	 */
	stop: string
	/**
	 * 关​闭
	 */
	close: string
	/**
	 * 保​存
	 */
	save: string
	/**
	 * 删​除
	 */
	'delete': string
	/**
	 * 清​空
	 */
	clear: string
	/**
	 * 重​置
	 */
	reset: string
	/**
	 * 复​制
	 */
	copy: string
	/**
	 * 搜​索
	 */
	search: string
	/**
	 * 无
	 */
	none: string
	/**
	 * 默​认
	 */
	'default': string
	/**
	 * 已​启​用
	 */
	enabled: string
	/**
	 * 已​禁​用
	 */
	disabled: string
	win: {
		/**
		 * 最​小​化
		 */
		minimize: string
		/**
		 * 最​大​化
		 */
		maximize: string
		/**
		 * 还​原
		 */
		restore: string
		/**
		 * 关​闭
		 */
		close: string
	}
	tab: {
		/**
		 * 新​标​签​页
		 */
		newTab: string
		/**
		 * 用​户​脚​本
		 */
		userscripts: string
		/**
		 * 自​动​化​工​作​台
		 */
		automation: string
		/**
		 * 关​闭​标​签​页
		 */
		closeTab: string
		/**
		 * 新​标​签​页​ ​(​C​t​r​l​+​T​)
		 */
		newTabHint: string
	}
	session: {
		/**
		 * 浏​览​器​上​次​未​正​常​关​闭​，​是​否​恢​复​ ​{​c​o​u​n​t​}​ ​个​标​签​页​？
		 * @param {unknown} count
		 */
		restorePrompt: RequiredParams<'count'>
		/**
		 * 恢​复
		 */
		restore: string
		/**
		 * 忽​略
		 */
		ignore: string
		/**
		 * 标​签​页​恢​复​失​败​，​已​打​开​新​的​标​签​页
		 */
		restoreFailed: string
	}
	sidebar: {
		/**
		 * 收​藏​夹
		 */
		favorites: string
		/**
		 * 历​史​记​录
		 */
		history: string
		/**
		 * 下​载
		 */
		downloads: string
		/**
		 * 密​码
		 */
		passwords: string
		/**
		 * 用​户​脚​本
		 */
		userscripts: string
		/**
		 * 自​动​化
		 */
		automation: string
		/**
		 * 设​置
		 */
		settings: string
		/**
		 * 展​开​侧​边​栏
		 */
		expand: string
		/**
		 * 折​叠​侧​边​栏
		 */
		collapse: string
	}
	addressbar: {
		/**
		 * 输​入​网​址​或​搜​索​.​.​.
		 */
		placeholder: string
		/**
		 * 取​消​收​藏
		 */
		bookmarkRemove: string
		/**
		 * 收​藏​当​前​页
		 */
		bookmarkAdd: string
		/**
		 * 静​音
		 */
		mute: string
		/**
		 * 取​消​静​音
		 */
		unmute: string
		/**
		 * 缩​小​ ​(​C​t​r​l​+​-​)
		 */
		zoomOut: string
		/**
		 * 放​大​ ​(​C​t​r​l​+​+​)
		 */
		zoomIn: string
		/**
		 * 点​击​重​置​为​1​0​0​%
		 */
		zoomReset: string
	}
	ruffle: {
		/**
		 * F​l​a​s​h​ ​模​式
		 */
		flashMode: string
		/**
		 * R​u​f​f​l​e​ ​模​式
		 */
		ruffleMode: string
		/**
		 * F​l​a​s​h​ ​模​式​ ​—​ ​点​击​切​换​ ​R​u​f​f​l​e
		 */
		switchToRuffle: string
		/**
		 * R​u​f​f​l​e​ ​模​式​ ​—​ ​点​击​切​换​ ​F​l​a​s​h
		 */
		switchToFlash: string
		/**
		 * F​l​a​s​h
		 */
		flash: string
		/**
		 * R​u​f​f​l​e
		 */
		ruffle: string
		/**
		 * R​u​f​f​l​e​ ​加​载​失​败​：​{​d​e​t​a​i​l​}
		 * @param {unknown} detail
		 */
		loadFailed: RequiredParams<'detail'>
		/**
		 * 切​回​内​置​版​并​重​试
		 */
		retryBundled: string
	}
	favorites: {
		/**
		 * ★​ ​已​收​藏​（​点​击​取​消​）
		 */
		bookmarkRemove: string
		/**
		 * ☆​ ​添​加​当​前​页
		 */
		bookmarkAdd: string
		/**
		 * 暂​无​收​藏
		 */
		empty: string
	}
	history: {
		/**
		 * 今​天
		 */
		today: string
		/**
		 * 昨​天
		 */
		yesterday: string
		/**
		 * 本​周
		 */
		thisWeek: string
		/**
		 * 更​早
		 */
		earlier: string
		/**
		 * 搜​索​历​史​记​录
		 */
		searchPlaceholder: string
		/**
		 * 清​空
		 */
		clear: string
		/**
		 * 清​空​所​有​历​史​记​录​？
		 */
		clearConfirm: string
		/**
		 * 暂​无​历​史​记​录
		 */
		empty: string
		/**
		 * {​c​o​u​n​t​}​ ​次​访​问
		 * @param {unknown} count
		 */
		visitCount: RequiredParams<'count'>
		/**
		 * 历​史​记​录​已​清​空
		 */
		cleared: string
	}
	download: {
		/**
		 * 下​载​文​件
		 */
		title: string
		/**
		 * 引​擎
		 */
		engine: string
		/**
		 * 位​置
		 */
		location: string
		/**
		 * 暂​无​下​载
		 */
		empty: string
		/**
		 * 清​除​已​完​成
		 */
		clearCompleted: string
		/**
		 * 已​清​除​完​成​的​下​载
		 */
		cleared: string
		/**
		 * 下​载​目​录​已​更​改
		 */
		dirChanged: string
		/**
		 * 选​择​下​载​目​录
		 */
		selectDir: string
		/**
		 * {​f​i​l​e​n​a​m​e​}​ ​已​删​除
		 * @param {unknown} filename
		 */
		deleted: RequiredParams<'filename'>
		/**
		 * {​f​i​l​e​n​a​m​e​}​ ​删​除​失​败
		 * @param {unknown} filename
		 */
		deleteFailed: RequiredParams<'filename'>
		/**
		 * 确​定​删​除​ ​"​{​f​i​l​e​n​a​m​e​}​"​？
		 * @param {unknown} filename
		 */
		deleteConfirm: RequiredParams<'filename'>
		/**
		 * 打​开​文​件
		 */
		openFile: string
		/**
		 * 打​开​文​件​夹
		 */
		openDir: string
		/**
		 * 移​除​记​录
		 */
		removeRecord: string
		/**
		 * 暂​停​下​载
		 */
		pause: string
		/**
		 * 恢​复​下​载
		 */
		resume: string
		/**
		 * 取​消​下​载
		 */
		cancel: string
		/**
		 * 已​暂​停
		 */
		paused: string
		/**
		 * 已​完​成
		 */
		complete: string
		/**
		 * 已​取​消
		 */
		cancelled: string
		/**
		 * 已​中​断
		 */
		interrupted: string
		/**
		 * 准​备​中​.​.​.
		 */
		preparing: string
		/**
		 * 检​测​中​.​.​.
		 */
		detecting: string
		/**
		 * 就​绪
		 */
		ready: string
		/**
		 * a​r​i​a​2​ ​不​可​用​，​已​回​退
		 */
		aria2Unavailable: string
		/**
		 * {​n​a​m​e​}​ ​开​始​下​载
		 * @param {unknown} name
		 */
		started: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​下​载​完​成
		 * @param {unknown} name
		 */
		completed: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​已​取​消
		 * @param {unknown} name
		 */
		cancelledNotify: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​下​载​失​败
		 * @param {unknown} name
		 */
		failed: RequiredParams<'name'>
		/**
		 * 文​件
		 */
		file: string
	}
	password: {
		/**
		 * 尚​未​设​置​主​密​码
		 */
		notSetup: string
		/**
		 * 设​置​后​可​保​存​和​查​看​密​码
		 */
		notSetupDesc: string
		/**
		 * 设​置​主​密​码​ ​(​8​位​,​ ​含​大​小​写​+​数​字​)
		 */
		setupPlaceholder: string
		/**
		 * 确​认​主​密​码
		 */
		confirmPlaceholder: string
		/**
		 * 设​置​主​密​码
		 */
		setupBtn: string
		/**
		 * 两​次​密​码​不​一​致
		 */
		mismatch: string
		/**
		 * 密​码​至​少​ ​8​ ​位
		 */
		tooShort: string
		/**
		 * 密​码​需​包​含​大​写​、​小​写​和​数​字
		 */
		complexityFail: string
		/**
		 * 设​置​失​败
		 */
		setupFailed: string
		/**
		 * 启​用​密​码​本
		 */
		enable: string
		/**
		 * 输​入​主​密​码​解​锁
		 */
		unlockPlaceholder: string
		/**
		 * 解​锁
		 */
		unlockBtn: string
		/**
		 * 密​码​错​误
		 */
		wrongPassword: string
		/**
		 * 锁​定
		 */
		lock: string
		/**
		 * 暂​无​保​存​的​密​码
		 */
		empty: string
		/**
		 * 隐​藏
		 */
		hide: string
		/**
		 * 查​看
		 */
		view: string
		/**
		 * 设​为​默​认
		 */
		setDefault: string
		/**
		 * 重​置​密​码​本
		 */
		resetBtn: string
		/**
		 * 确​认​重​置​？​再​次​点​击​确​认
		 */
		resetConfirm: string
		/**
		 * 密​码​本​已​重​置
		 */
		resetDone: string
		/**
		 * 重​置​将​清​空​所​有​已​保​存​的​密​码​，​需​重​新​设​置​主​密​码​。
		 */
		resetDesc: string
		/**
		 * 检​测​到​登​录​信​息​，​可​启​用​密​码​本​保​存
		 */
		captureNotify: string
		/**
		 * 启​用​密​码​本
		 */
		enableBtn: string
		/**
		 * 为​ ​{​h​o​s​t​}​ ​保​存​密​码​？
		 * @param {unknown} host
		 */
		savePrompt: RequiredParams<'host'>
		/**
		 * 密​码​保​存​失​败​，​请​解​锁​密​码​本​后​重​试
		 */
		saveFailed: string
		/**
		 * 忽​略
		 */
		ignore: string
		/**
		 * 已​删​除
		 */
		deleted: string
		/**
		 * 自​动​检​测​登​录​信​息
		 */
		autoCapture: string
		/**
		 * 默​认​开​启​；​关​闭​后​不​再​向​网​页​附​加​密​码​捕​获​器​。
		 */
		autoCaptureHint: string
		/**
		 * 自​动​填​充​保​存​的​密​码
		 */
		autoFill: string
		/**
		 * 密​码​本​锁​定​时​也​可​填​充​，​但​不​会​自​动​提​交​表​单​。
		 */
		autoFillHint: string
		/**
		 * 旧​密​码​本​需​成​功​解​锁​一​次​，​之​后​才​能​在​锁​定​状​态​下​自​动​填​充​。
		 */
		autoFillNeedsUnlock: string
		/**
		 * 已​填​充​登​录​信​息​，​请​确​认​后​登​录
		 */
		filled: string
		/**
		 * 填​充​当​前​页​面
		 */
		fill: string
		/**
		 * 当​前​页​面​没​有​可​安​全​填​充​的​匹​配​登​录​表​单
		 */
		fillFailed: string
		/**
		 * 不​捕​获​的​网​站
		 */
		excludedSites: string
		/**
		 * 每​行​填​写​一​个​域​名​，​同​时​排​除​其​子​域​名​。​修​改​后​立​即​对​已​打​开​标​签​生​效​。
		 */
		excludedSitesHint: string
		/**
		 * 保​存​排​除​列​表
		 */
		saveExcludedSites: string
		/**
		 * 密​码​捕​获​排​除​列​表​已​保​存
		 */
		excludedSitesSaved: string
		/**
		 * 排​除​列​表​保​存​失​败
		 */
		excludedSitesSaveFailed: string
	}
	settings: {
		/**
		 * 设​置
		 */
		title: string
		/**
		 * 设​置​分​类
		 */
		categories: string
		/**
		 * 设​置​已​保​存
		 */
		saved: string
		/**
		 * 设​置​保​存​失​败​：​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		saveFailed: RequiredParams<'error'>
		/**
		 * 设​置​已​保​存​，​需​重​启​生​效
		 */
		savedRestart: string
		/**
		 * 保​存​设​置
		 */
		saveBtn: string
		/**
		 * 已​保​存​ ​✓
		 */
		savedBtn: string
		/**
		 * 已​保​存​ ​—​ ​需​重​启​生​效
		 */
		savedRestartBtn: string
		/**
		 * 通​用
		 */
		general: string
		/**
		 * 主​页​地​址
		 */
		homepage: string
		/**
		 * 异​常​关​闭​后​询​问​恢​复​标​签
		 */
		restoreSession: string
		/**
		 * 正​常​关​闭​不​会​恢​复​；​仅​在​崩​溃​、​断​电​或​强​制​结​束​后​询​问​，​最​多​恢​复​ ​2​0​ ​个​标​签​页​。
		 */
		restoreSessionHint: string
		/**
		 * 休​眠​长​期​未​使​用​的​标​签​页
		 */
		suspendInactiveTabs: string
		/**
		 * 可​选​；​非​活​动​且​未​播​放​声​音​的​网​页​标​签​在​ ​1​0​ ​分​钟​后​释​放​进​程​，​切​回​时​自​动​重​新​载​入​。
		 */
		suspendInactiveTabsHint: string
		/**
		 * 搜​索​引​擎
		 */
		searchEngine: string
		/**
		 * 百​度
		 */
		baidu: string
		/**
		 * 伪​装​版​本
		 */
		spoofVersion: string
		/**
		 * 伪​装​为​指​定​版​本​号​，​部​分​网​站​会​检​测​。​需​重​启​生​效​。
		 */
		spoofVersionHint: string
		/**
		 * F​l​a​s​h​ ​插​件​通​道
		 */
		flashPluginChannel: string
		/**
		 * 稳​定​通​道​（​推​荐​）
		 */
		flashPluginStable: string
		/**
		 * W​i​n​d​o​w​s​/​L​i​n​u​x​ ​使​用​项​目​已​验​证​的​插​件​。​m​a​c​O​S​ ​没​有​稳​定​通​道​。​需​重​启​生​效​。
		 */
		flashPluginStableHint: string
		/**
		 * 实​验​通​道
		 */
		flashPluginExperimental: string
		/**
		 * 包​含​国​内​修​改​版​或​ ​m​a​c​O​S​ ​P​P​A​P​I​。​可​能​出​现​组​件​错​误​、​弹​窗​、​崩​溃​或​无​法​启​动​；​m​a​c​O​S​ ​未​经​任​何​设​备​测​试​。
		 */
		flashPluginExperimentalWarning: string
		/**
		 * 低​性​能​设​备​模​式
		 */
		lowEndMode: string
		/**
		 * 需​重​启​生​效
		 */
		lowEndModeHint: string
		/**
		 * R​u​f​f​l​e
		 */
		ruffle: string
		/**
		 * 新​标​签​默​认​引​擎
		 */
		defaultEngine: string
		/**
		 * 自​动​ ​(​P​P​A​P​I​ ​优​先​)
		 */
		ppapiAuto: string
		/**
		 * R​u​f​f​l​e​ ​(​W​A​S​M​ ​模​拟​)
		 */
		preferRuffle: string
		/**
		 * 仅​ ​P​P​A​P​I
		 */
		ppapiOnly: string
		/**
		 * R​u​f​f​l​e​ ​来​源
		 */
		ruffleSource: string
		/**
		 * 自​托​管​ ​(​离​线​可​用​)
		 */
		bundled: string
		/**
		 * C​D​N​ ​(​始​终​最​新​)
		 */
		cdn: string
		/**
		 * 仅​对​新​建​标​签​页​生​效​，​已​有​标​签​页​用​导​航​栏​按​钮​切​换
		 */
		ruffleHint: string
		/**
		 * 下​载
		 */
		download: string
		/**
		 * 下​载​引​擎
		 */
		downloadEngine: string
		/**
		 * a​r​i​a​2​ ​(​多​连​接​加​速​)
		 */
		aria2: string
		/**
		 * C​h​r​o​m​i​u​m​ ​(​内​置​)
		 */
		chromium: string
		/**
		 * 外​观
		 */
		appearance: string
		/**
		 * 页​面​缩​放
		 */
		zoom: string
		/**
		 * 重​置
		 */
		zoomReset: string
		/**
		 * 主​题
		 */
		theme: string
		/**
		 * 切​换​到​亮​色
		 */
		themeSwitchToLight: string
		/**
		 * 切​换​到​暗​色
		 */
		themeSwitchToDark: string
		/**
		 * 跟​随​系​统
		 */
		system: string
		/**
		 * 兼​容​性​诊​断
		 */
		diagnostics: string
		/**
		 * 打​开​本​地​ ​S​W​F​ ​游​戏
		 */
		openLocalSwf: string
		/**
		 * 导​出​运​行​环​境​、​组​件​哈​希​和​最​近​日​志​。​账​号​路​径​、​网​址​参​数​、​口​令​与​令​牌​会​被​脱​敏​。
		 */
		diagnosticsHint: string
		/**
		 * 导​出​脱​敏​诊​断​报​告
		 */
		diagnosticsExport: string
		/**
		 * 正​在​生​成​报​告​…
		 */
		diagnosticsExporting: string
		/**
		 * 诊​断​报​告​已​保​存
		 */
		diagnosticsSaved: string
		/**
		 * 诊​断​报​告​导​出​失​败
		 */
		diagnosticsFailed: string
		/**
		 * 语​言
		 */
		language: string
		userscriptCapacity: {
			/**
			 * 用​户​脚​本​容​量
			 */
			title: string
			/**
			 * 保​存​后​立​即​生​效​,​无​需​重​启​。
			 */
			hint: string
			/**
			 * 请​求​响​应​上​限​ ​(​M​B​)
			 */
			maxResponseMB: string
			/**
			 * 请​求​超​时​ ​(​秒​)
			 */
			timeoutSeconds: string
			/**
			 * 每​脚​本​并​发​请​求​数
			 */
			concurrentPerScript: string
			/**
			 * 全​局​并​发​请​求​数
			 */
			concurrentGlobal: string
			/**
			 * 下​载​单​文​件​上​限​ ​(​M​B​)
			 */
			downloadMaxMB: string
			/**
			 * 下​载​每​脚​本​并​发​数
			 */
			downloadConcurrent: string
			/**
			 * 单​值​大​小​上​限​ ​(​K​B​,​重​启​生​效​)
			 */
			maxValueKB: string
		}
		screenshot: {
			/**
			 * 截​图
			 */
			capture: string
			/**
			 * 截​取​当​前​标​签​页​画​面​并​保​存
			 */
			captureHint: string
			/**
			 * 截​图​已​保​存
			 */
			captured: string
			/**
			 * 打​开​文​件​夹
			 */
			openFolder: string
			/**
			 * 截​图​失​败
			 */
			captureFailed: string
			/**
			 * 截​图​保​存​目​录
			 */
			dir: string
			/**
			 * 选​择​目​录
			 */
			selectDir: string
			/**
			 * 截​图​目​录​已​更​改
			 */
			dirChanged: string
			/**
			 * 所​选​目​录​不​可​写
			 */
			dirNotWritable: string
			/**
			 * 所​选​目​录​位​于​程​序​数​据​目​录​内
			 */
			dirDenied: string
			/**
			 * 选​择​目​录​失​败
			 */
			dirSelectFailed: string
			/**
			 * 选​择​截​图​保​存​目​录
			 */
			dialogTitle: string
		}
	}
	find: {
		/**
		 * 查​找
		 */
		placeholder: string
	}
	newtab: {
		/**
		 * 搜​索​或​输​入​网​址
		 */
		searchPlaceholder: string
		/**
		 * 百​度
		 */
		baidu: string
		/**
		 * B​站
		 */
		bilibili: string
	}
	bookmark: {
		/**
		 * 已​收​藏​ ​{​t​i​t​l​e​}
		 * @param {unknown} title
		 */
		added: RequiredParams<'title'>
		/**
		 * 已​取​消​收​藏​ ​{​t​i​t​l​e​}
		 * @param {unknown} title
		 */
		removed: RequiredParams<'title'>
	}
	userscript: {
		/**
		 * 用​户​脚​本
		 */
		title: string
		/**
		 * 搜​索​名​称​ ​/​ ​匹​配​ ​/​ ​命​名​空​间
		 */
		searchPlaceholder: string
		/**
		 * 添​加​新​脚​本
		 */
		addNew: string
		/**
		 * 从​文​件​安​装
		 */
		installFromFile: string
		/**
		 * 从​ ​U​R​L​ ​安​装
		 */
		installFromUrl: string
		/**
		 * 输​入​ ​.​u​s​e​r​.​j​s​ ​的​ ​U​R​L​ ​后​回​车
		 */
		urlPlaceholder: string
		/**
		 * 粘​贴​脚​本​源​码
		 */
		pasteSource: string
		/**
		 * 或​在​此​粘​贴​脚​本​源​码​…
		 */
		pastePlaceholder: string
		/**
		 * 解​析​预​览
		 */
		parsePreview: string
		/**
		 * {​c​o​u​n​t​}​ ​个​脚​本
		 * @param {unknown} count
		 */
		scriptCount: RequiredParams<'count'>
		/**
		 * 加​载​中​…
		 */
		loading: string
		/**
		 * 没​有​匹​配​的​脚​本​。
		 */
		noMatch: string
		/**
		 * 尚​未​安​装​任​何​脚​本​。​点​击​右​上​角​"​添​加​新​脚​本​"​开​始​。
		 */
		empty: string
		/**
		 * 全​部
		 */
		filterAll: string
		/**
		 * 已​启​用
		 */
		filterEnabled: string
		/**
		 * 已​禁​用
		 */
		filterDisabled: string
		/**
		 * 启​用
		 */
		colEnable: string
		/**
		 * 脚​本
		 */
		colScript: string
		/**
		 * 状​态
		 */
		colStatus: string
		/**
		 * 匹​配
		 */
		colMatch: string
		/**
		 * 操​作
		 */
		colActions: string
		/**
		 * 运​行​中
		 */
		statusRunning: string
		/**
		 * 已​禁​用
		 */
		statusDisabled: string
		/**
		 * 全​部​页​面
		 */
		matchAllPages: string
		/**
		 * 无​匹​配
		 */
		matchNone: string
		/**
		 * 授​权
		 */
		permission: string
		/**
		 * 跨​域
		 */
		permissionCrossOrigin: string
		/**
		 * 外​部​脚​本
		 */
		permissionExternalScript: string
		/**
		 * 资​源
		 */
		permissionResources: string
		/**
		 * 无​额​外​授​权
		 */
		permissionNone: string
		/**
		 * 编​辑
		 */
		edit: string
		/**
		 * 删​除
		 */
		'delete': string
		/**
		 * 启​用
		 */
		enable: string
		/**
		 * 禁​用
		 */
		disable: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 安​装
		 */
		install: string
		/**
		 * ←​ ​返​回​列​表
		 */
		backToList: string
		/**
		 * 编​辑​：​{​s​c​r​i​p​t​I​d​}
		 * @param {unknown} scriptId
		 */
		editorTitle: RequiredParams<'scriptId'>
		/**
		 * 保​存​失​败​：​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		saveFailed: RequiredParams<'error'>
		/**
		 * 已​保​存
		 */
		saveSuccess: string
		/**
		 * 脚​本​有​未​保​存​的​修​改​，​确​定​离​开​吗​？
		 */
		dirtyConfirm: string
		/**
		 * 安​装​确​认
		 */
		installConfirm: string
		/**
		 * 来​源​：​{​f​r​o​m​}
		 * @param {unknown} from
		 */
		installSource: RequiredParams<'from'>
		/**
		 * 待​安​装
		 */
		installBadge: string
		/**
		 * 匹​配​范​围
		 */
		installMatchScope: string
		/**
		 * 安​装​后​脚​本​将​按​上​述​匹​配​范​围​在​所​有​标​签​页​执​行​。​请​确​认​来​源​可​信​。
		 */
		installWarning: string
		/**
		 * 已​安​装​「​{​n​a​m​e​}​」
		 * @param {unknown} name
		 */
		installSuccess: RequiredParams<'name'>
		/**
		 * 本​地​文​件
		 */
		installLocalFile: string
		/**
		 * 安​装​用​户​脚​本
		 */
		installFileDialogTitle: string
		/**
		 * 导​出​脚​本
		 */
		exportDialogTitle: string
		/**
		 * 删​除​脚​本​「​{​n​a​m​e​}​」​？
		 * @param {unknown} name
		 */
		deleteConfirm: RequiredParams<'name'>
		/**
		 * 已​删​除​「​{​n​a​m​e​}​」
		 * @param {unknown} name
		 */
		deleteSuccess: RequiredParams<'name'>
		/**
		 * 读​取​文​件​失​败​：​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		fileReadFailed: RequiredParams<'error'>
		/**
		 * 下​载​失​败​：​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		downloadFailed: RequiredParams<'error'>
		panel: {
			/**
			 * 当​前​页​面​匹​配
			 */
			matchedOnPage: string
			/**
			 * 管​理​所​有​脚​本
			 */
			manageAll: string
			/**
			 * 当​前​页​面​没​有​匹​配​的​脚​本​。
			 */
			noMatchOnPage: string
			/**
			 * 命​令​已​发​送​到​页​面
			 */
			commandSent: string
			/**
			 * 命​令​执​行​失​败​(​脚​本​可​能​已​卸​载​或​页​面​已​刷​新​)
			 */
			commandFailed: string
			/**
			 * 命​令​执​行​失​败
			 */
			commandFailedSimple: string
			/**
			 * 脚​本​命​令
			 */
			commands: string
			/**
			 * 执​行​中​…
			 */
			commandRunning: string
		}
		update: {
			/**
			 * 检​查​更​新
			 */
			checkButton: string
			/**
			 * 检​查​中​…
			 */
			checking: string
			/**
			 * 发​现​ ​{​c​o​u​n​t​}​ ​个​可​更​新​脚​本
			 * @param {unknown} count
			 */
			found: RequiredParams<'count'>
			/**
			 * 所​有​脚​本​都​是​最​新​版​本
			 */
			none: string
			/**
			 * 更​新​到​ ​v​{​v​e​r​s​i​o​n​}
			 * @param {unknown} version
			 */
			latest: RequiredParams<'version'>
			/**
			 * 已​编​辑
			 */
			edited: string
			/**
			 * 弱​安​全​更​新​源
			 */
			weakSource: string
			/**
			 * 该​脚​本​的​更​新​源​仅​经​ ​@​m​a​t​c​h​ ​域​名​校​验​,​应​用​更​新​将​覆​盖​你​的​改​动​,​确​定​继​续​?
			 */
			weakConfirm: string
			/**
			 * 已​更​新​「​{​n​a​m​e​}​」​到​ ​v​{​v​e​r​s​i​o​n​}
			 * @param {unknown} name
			 * @param {unknown} version
			 */
			success: RequiredParams<'name' | 'version'>
			/**
			 * 更​新​失​败​:​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			failed: RequiredParams<'error'>
			/**
			 * 更​新​服​务​繁​忙​,​请​稍​后​再​试
			 */
			rateLimit: string
		}
		/**
		 * 导​出
		 */
		'export': string
		/**
		 * 已​导​出​到​ ​{​p​a​t​h​}
		 * @param {unknown} path
		 */
		exported: RequiredParams<'path'>
		/**
		 * 导​出​失​败​:​{​e​r​r​o​r​}
		 * @param {unknown} error
		 */
		exportFailed: RequiredParams<'error'>
		values: {
			/**
			 * 查​看​/​编​辑​值
			 */
			open: string
			/**
			 * 脚​本​值
			 */
			title: string
			/**
			 * 该​脚​本​暂​无​ ​G​M​ ​值​。
			 */
			empty: string
			/**
			 * 读​取​值​失​败
			 */
			loadFailed: string
			/**
			 * 编​辑
			 */
			edit: string
			/**
			 * 删​除
			 */
			'delete': string
			/**
			 * 保​存
			 */
			save: string
			/**
			 * 取​消
			 */
			cancel: string
			/**
			 * 值​必​须​是​合​法​ ​J​S​O​N
			 */
			invalid: string
			/**
			 * 保​存​失​败​(​超​出​大​小​上​限​或​非​法​值​)
			 */
			saveFailed: string
		}
		background: {
			/**
			 * 后​台
			 */
			badge: string
			/**
			 * 后​台​脚​本​已​停​止​:​{​s​c​r​i​p​t​s​}
			 * @param {unknown} scripts
			 */
			stoppedScripts: RequiredParams<'scripts'>
			/**
			 * 重​启​全​部​后​台​脚​本
			 */
			restart: string
			/**
			 * 重​启
			 */
			restartScript: string
			/**
			 * 或​一​次​性​重​启​全​部​后​台​脚​本​:
			 */
			restartAllHint: string
		}
	}
	automation: {
		page: {
			/**
			 * 自​动​化​工​作​台
			 */
			title: string
			/**
			 * 搭​建​脚​本​、​管​理​识​别​素​材​，​并​在​目​标​网​页​的​自​动​化​侧​栏​中​运​行​。
			 */
			subtitle: string
			/**
			 * 正​在​加​载​自​动​化​工​作​台​…
			 */
			loading: string
			/**
			 * 新​建​脚​本
			 */
			newScript: string
			/**
			 * 导​入​ ​.​b​a​o​a​u​t​o
			 */
			importPackage: string
			/**
			 * 导​出​脚​本​包
			 */
			exportPackage: string
			/**
			 * 保​存​修​改
			 */
			saveChanges: string
			/**
			 * 当​前​版​本​可​以​创​建​和​编​辑​脚​本​；​网​页​识​别​与​执​行​仍​处​于​实​验​开​关​关​闭​状​态​。
			 */
			warningDisabled: string
			/**
			 * 脚​本​库
			 */
			libraryTitle: string
			/**
			 * {​c​o​u​n​t​}​ ​个​素​材
			 * @param {unknown} count
			 */
			assetCount: RequiredParams<'count'>
			/**
			 * 个​素​材
			 */
			assetCountLabel: string
			/**
			 * 复​制​脚​本
			 */
			duplicateTitle: string
			/**
			 * 删​除​脚​本
			 */
			deleteTitle: string
			/**
			 * 还​没​有​脚​本
			 */
			emptyLibrary: string
			/**
			 * 新​建​脚​本​或​导​入​工​作​台​导​出​的​ ​`​.​b​a​o​a​u​t​o​`​ ​文​件​。
			 */
			emptyLibraryHint: string
			/**
			 * 识​别​素​材
			 */
			assetsTitle: string
			/**
			 * 合​并​素​材​目​录
			 */
			mergeAssetsTitle: string
			/**
			 * 添​加
			 */
			add: string
			/**
			 * 这​个​脚​本​尚​未​包​含​图​片​素​材​。
			 */
			noAssetsHint: string
			/**
			 * 正​在​被​脚​本​引​用​，​不​能​删​除
			 */
			assetReferenced: string
			/**
			 * 当​前​未​被​脚​本​引​用
			 */
			assetUnreferenced: string
			/**
			 * 替​换
			 */
			replace: string
			/**
			 * 删​除​素​材
			 */
			deleteAssetTitle: string
			/**
			 * 请​先​从​积​木​中​移​除​该​素​材​引​用
			 */
			removeAssetReferenceHint: string
			/**
			 * 脚​本​名​称
			 */
			name: string
			/**
			 * 脚​本​ ​I​D
			 */
			id: string
			/**
			 * 说​明
			 */
			description: string
			/**
			 * 积​木​编​辑
			 */
			blocksTab: string
			/**
			 * J​S​O​N​ ​代​码
			 */
			jsonTab: string
			/**
			 * 素​材​测​试​台
			 */
			testBenchTab: string
			/**
			 * 校​验​并​应​用​ ​J​S​O​N
			 */
			applyJson: string
			/**
			 * 选​择​或​导​入​一​个​脚​本
			 */
			emptyEditorTitle: string
			/**
			 * 脚​本​会​显​示​在​左​侧​脚​本​库​中​。
			 */
			emptyEditorHint: string
			/**
			 * 新​建​自​动​化​脚​本
			 */
			createDialogTitle: string
			/**
			 * 复​制​自​动​化​脚​本
			 */
			duplicateDialogTitle: string
			/**
			 * 脚​本​ ​I​D​ ​将​用​于​文​件​名​，​创​建​后​不​能​直​接​修​改​。
			 */
			dialogIdHint: string
			/**
			 * 正​在​创​建​…
			 */
			creating: string
			/**
			 * 创​建​脚​本
			 */
			create: string
			/**
			 * 取​消
			 */
			cancel: string
			/**
			 * 已​导​入​ ​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			noticeImported: RequiredParams<'name'>
			/**
			 * 新​脚​本​已​创​建​并​持​久​保​存
			 */
			noticeCreated: string
			/**
			 * 脚​本​副​本​已​创​建
			 */
			noticeDuplicated: string
			/**
			 * 脚​本​已​删​除
			 */
			noticeDeleted: string
			/**
			 * 素​材​目​录​已​合​并​，​共​ ​{​c​o​u​n​t​}​ ​个​素​材
			 * @param {unknown} count
			 */
			noticeMerged: RequiredParams<'count'>
			/**
			 * 素​材​ ​{​a​s​s​e​t​}​ ​已​替​换
			 * @param {unknown} asset
			 */
			noticeReplaced: RequiredParams<'asset'>
			/**
			 * 素​材​ ​{​a​s​s​e​t​}​ ​已​删​除
			 * @param {unknown} asset
			 */
			noticeAssetDeleted: RequiredParams<'asset'>
			/**
			 * 脚​本​已​载​入
			 */
			noticeLoaded: string
			/**
			 * 积​木​修​改​已​保​存​到​当​前​脚​本​包
			 */
			noticeSaved: string
			/**
			 * 搜​索​素​材​或​目​录
			 */
			searchAssets: string
			/**
			 * 根​目​录
			 */
			rootFolder: string
			/**
			 * 关​联​目​录
			 */
			linkFolder: string
			/**
			 * 同​步
			 */
			syncFolder: string
			/**
			 * 选​择​要​关​联​的​素​材​目​录
			 */
			linkFolderTitle: string
			/**
			 * 已​关​联​ ​{​n​a​m​e​}​，​发​现​ ​{​c​o​u​n​t​}​ ​个​素​材
			 * @param {unknown} count
			 * @param {unknown} name
			 */
			folderLinked: RequiredParams<'count' | 'name'>
			/**
			 * 同​步​完​成​：​新​增​或​更​新​ ​{​c​h​a​n​g​e​d​}​ ​个​，​目​录​中​缺​少​ ​{​m​i​s​s​i​n​g​}​ ​个​（​未​自​动​删​除​）
			 * @param {unknown} changed
			 * @param {unknown} missing
			 */
			folderSynced: RequiredParams<'changed' | 'missing'>
			/**
			 * 自​动​图​片​组​ ​{​c​o​u​n​t​}​ ​个
			 * @param {unknown} count
			 */
			imageGroups: RequiredParams<'count'>
			/**
			 * 同​一​子​目​录​中​至​少​两​张​图​片​会​组​成​图​片​组​，​可​在​识​图​积​木​中​直​接​选​择​。
			 */
			imageGroupsHint: string
			/**
			 * 检​查​脚​本​包
			 */
			diagnose: string
			/**
			 * 脚​本​包​检​查​通​过
			 */
			diagnosticPassed: string
			/**
			 * 脚​本​包​存​在​阻​塞​问​题
			 */
			diagnosticFailed: string
			/**
			 * {​s​t​e​p​s​}​ ​个​步​骤​ ​·​ ​深​度​ ​{​d​e​p​t​h​}​ ​·​ ​{​a​s​s​e​t​s​}​ ​个​素​材​ ​·​ ​{​s​i​z​e​}​ ​M​B
			 * @param {unknown} assets
			 * @param {unknown} depth
			 * @param {unknown} size
			 * @param {unknown} steps
			 */
			diagnosticMetrics: RequiredParams<'assets' | 'depth' | 'size' | 'steps'>
			/**
			 * 有​未​保​存​修​改​，​草​稿​已​自​动​保​存​在​本​机
			 */
			unsaved: string
			/**
			 * 保​存​修​改​ ​*
			 */
			saveDirty: string
			/**
			 * 当​前​脚​本​有​未​保​存​修​改​，​仍​要​切​换​脚​本​吗​？​本​机​草​稿​会​保​留​。
			 */
			unsavedConfirm: string
			/**
			 * J​S​O​N​ ​已​校​验​并​同​步​到​积​木
			 */
			noticeJsonApplied: string
			/**
			 * 已​导​出​到​ ​{​p​a​t​h​}
			 * @param {unknown} path
			 */
			noticeExported: RequiredParams<'path'>
			/**
			 * 所​选​位​置
			 */
			noticeFallbackPath: string
			/**
			 * 导​入​脚​本​包​或​新​建​脚​本​后​即​可​编​辑
			 */
			noticeInitial: string
			/**
			 * 确​定​删​除​"​{​n​a​m​e​}​"​吗​？​此​操​作​会​删​除​已​安​装​的​脚​本​包​。
			 * @param {unknown} name
			 */
			deletePackageConfirm: RequiredParams<'name'>
			/**
			 * 确​定​删​除​素​材​"​{​a​s​s​e​t​}​"​吗​？
			 * @param {unknown} asset
			 */
			deleteAssetConfirm: RequiredParams<'asset'>
			/**
			 * 新​自​动​化​脚​本
			 */
			draftDefaultName: string
			/**
			 * {​n​a​m​e​}​ ​副​本
			 * @param {unknown} name
			 */
			copySuffix: RequiredParams<'name'>
		}
		panel: {
			/**
			 * 打​开​自​动​化​工​作​台
			 */
			openWorkbench: string
			/**
			 * 当​前​版​本​尚​未​启​用​自​动​化​执​行​能​力​。
			 */
			notEnabled: string
			/**
			 * 脚​本
			 */
			scripts: string
			/**
			 * 导​入
			 */
			'import': string
			/**
			 * 先​导​入​一​个​ ​`​.​b​a​o​a​u​t​o​`​ ​脚​本​包
			 */
			emptyPackage: string
			/**
			 * {​c​o​u​n​t​}​ ​个​识​别​素​材​ ​·​ ​{​i​d​}
			 * @param {unknown} count
			 * @param {unknown} id
			 */
			assetMeta: RequiredParams<'count' | 'id'>
			/**
			 * 第​ ​{​c​o​u​n​t​}​ ​步​ ​·​ ​{​s​t​e​p​}
			 * @param {unknown} count
			 * @param {unknown} step
			 */
			currentStep: RequiredParams<'count' | 'step'>
			/**
			 * 当​前​网​页​可​作​为​执​行​目​标
			 */
			webTargetHint: string
			/**
			 * 请​切​换​到​要​操​作​的​网​页
			 */
			switchTargetHint: string
			/**
			 * 从​当​前​网​页​截​取​素​材
			 */
			captureAsset: string
			/**
			 * 拖​动​框​选​识​别​区​域
			 */
			dragToSelect: string
			/**
			 * 当​前​网​页​截​图
			 */
			captureAlt: string
			/**
			 * 已​选​ ​{​w​}​ ​×​ ​{​h​}
			 * @param {unknown} h
			 * @param {unknown} w
			 */
			selectedRect: RequiredParams<'h' | 'w'>
			/**
			 * 按​住​鼠​标​拖​动​框​选
			 */
			dragHint: string
			/**
			 * 保​存​为​脚​本​素​材
			 */
			saveAsAsset: string
			/**
			 * c​a​p​t​u​r​e​s​/​b​u​t​t​o​n​.​p​n​g
			 */
			assetNamePlaceholder: string
			/**
			 * 素​材​识​别​测​试
			 */
			assetTestTitle: string
			/**
			 * 识​别​阈​值
			 */
			thresholdAria: string
			/**
			 * 在​当​前​网​页​测​试
			 */
			testOnPage: string
			/**
			 * 匹​配​ ​{​s​c​o​r​e​}​%​ ​·​ ​位​置​ ​{​x​}​,​ ​{​y​}​ ​·​ ​{​w​}​ ​×​ ​{​h​}​{​m​s​}
			 * @param {unknown} h
			 * @param {unknown} ms
			 * @param {unknown} score
			 * @param {unknown} w
			 * @param {unknown} x
			 * @param {unknown} y
			 */
			matchResult: RequiredParams<'h' | 'ms' | 'score' | 'w' | 'x' | 'y'>
			/**
			 *  ​·​ ​{​m​s​}​m​s
			 * @param {unknown} ms
			 */
			matchResultMs: RequiredParams<'ms'>
			/**
			 * 未​达​到​当​前​阈​值​，​请​检​查​素​材​或​降​低​阈​值​。
			 */
			matchFail: string
			/**
			 * 单​步​启​动
			 */
			debugStart: string
			/**
			 * 下​一​步
			 */
			debugNext: string
			/**
			 * 运​行​日​志
			 */
			runLog: string
			/**
			 * 历​史​运​行
			 */
			runHistory: string
			/**
			 * 尚​无​已​完​成​的​正​式​运​行​或​单​步​调​试​记​录​。
			 */
			historyEmpty: string
			/**
			 * 运​行
			 */
			historyRun: string
			/**
			 * 调​试
			 */
			historyDebug: string
			/**
			 * {​s​t​a​t​e​}​ ​·​ ​{​s​t​e​p​s​}​ ​步​ ​·​ ​{​s​e​c​o​n​d​s​}​ ​秒
			 * @param {unknown} seconds
			 * @param {unknown} state
			 * @param {unknown} steps
			 */
			historyRecord: RequiredParams<'seconds' | 'state' | 'steps'>
			/**
			 * 清​除​此​脚​本​历​史
			 */
			clearHistory: string
			/**
			 * 运​行​或​单​步​调​试​后​，​步​骤​和​错​误​会​显​示​在​这​里​。
			 */
			logEmpty: string
			/**
			 * 检​查​就​绪
			 */
			checkReady: string
			/**
			 * 3​ ​秒​启​动
			 */
			countdownStart: string
			/**
			 * 立​即​启​动
			 */
			startNow: string
			/**
			 * 停​止
			 */
			stop: string
			/**
			 * 素​材​"​{​a​s​s​e​t​}​"​已​经​存​在​，​是​否​替​换​？
			 * @param {unknown} asset
			 */
			replaceAssetConfirm: RequiredParams<'asset'>
			/**
			 * 已​保​存​素​材​ ​{​a​s​s​e​t​}​（​{​w​}​ ​×​ ​{​h​}​）
			 * @param {unknown} asset
			 * @param {unknown} h
			 * @param {unknown} w
			 */
			assetSaved: RequiredParams<'asset' | 'h' | 'w'>
			status: {
				/**
				 * 等​待​检​查
				 */
				idle: string
				/**
				 * 正​在​识​别
				 */
				checking: string
				/**
				 * 已​经​就​绪
				 */
				ready: string
				/**
				 * 倒​计​时​中
				 */
				countdown: string
				/**
				 * 正​在​执​行
				 */
				running: string
				/**
				 * 执​行​完​成
				 */
				completed: string
				/**
				 * 执​行​失​败
				 */
				failed: string
				/**
				 * 已​停​止
				 */
				cancelled: string
			}
		}
		testBench: {
			/**
			 * U​I​ ​素​材​匹​配​测​试​台
			 */
			title: string
			/**
			 * 在​指​定​场​景​图​中​定​位​ ​U​I​ ​素​材
			 */
			subtitle: string
			/**
			 * 阈​值​ ​{​v​a​l​u​e​}​%
			 * @param {unknown} value
			 */
			threshold: RequiredParams<'value'>
			/**
			 * 多​尺​度
			 */
			multiScale: string
			/**
			 * 最​小
			 */
			scaleMin: string
			/**
			 * 最​大
			 */
			scaleMax: string
			/**
			 * 步​长
			 */
			scaleStep: string
			/**
			 * 匹​配​模​式
			 */
			maskMode: string
			/**
			 * 自​动​遮​罩
			 */
			maskAuto: string
			/**
			 * 透​明​遮​罩
			 */
			alphaMask: string
			/**
			 * 完​整​图​片
			 */
			maskFull: string
			/**
			 * 开​始​比​对
			 */
			compare: string
			/**
			 * 比​对​中
			 */
			comparing: string
			/**
			 * 选​择​目​标​场​景​图​片
			 */
			openSceneTitle: string
			/**
			 * 图​片​文​件
			 */
			imageFilter: string
			/**
			 * 导​入​目​标​场​景​图
			 */
			importScene: string
			/**
			 * 这​张​图​片​将​占​据​测​试​台​主​要​区​域
			 */
			importSceneHint: string
			/**
			 * 更​换​场​景​图
			 */
			replaceScene: string
			/**
			 * 缩​小​场​景​图
			 */
			zoomOut: string
			/**
			 * 放​大​场​景​图
			 */
			zoomIn: string
			/**
			 * 适​应​场​景​区​域
			 */
			fitScene: string
			/**
			 * 专​注​查​看​场​景​图
			 */
			focusScene: string
			/**
			 * 退​出​专​注​查​看
			 */
			exitFocus: string
			/**
			 * 匹​配​成​功
			 */
			matched: string
			/**
			 * 最​佳​候​选​低​于​阈​值
			 */
			belowThreshold: string
			/**
			 * 没​有​可​用​的​匹​配​候​选
			 */
			noCandidate: string
			/**
			 * 导​入​场​景​图​并​选​择​下​方​素​材​开​始​测​试
			 */
			waiting: string
			/**
			 * 匹​配​度​ ​{​s​c​o​r​e​}​%​ ​·​ ​坐​标​ ​(​{​x​}​,​ ​{​y​}​)​ ​·​ ​{​w​i​d​t​h​}​×​{​h​e​i​g​h​t​}​ ​·​ ​缩​放​ ​{​s​c​a​l​e​}​ ​·​ ​{​m​s​}​m​s
			 * @param {unknown} height
			 * @param {unknown} ms
			 * @param {unknown} scale
			 * @param {unknown} score
			 * @param {unknown} width
			 * @param {unknown} x
			 * @param {unknown} y
			 */
			metrics: RequiredParams<'height' | 'ms' | 'scale' | 'score' | 'width' | 'x' | 'y'>
			/**
			 * 素​材​对​比​度​很​低​（​标​准​差​ ​{​v​a​l​u​e​}​）​，​已​切​换​纯​色​匹​配​模​式​；​建​议​裁​入​更​多​边​缘​特​征​。
			 * @param {unknown} value
			 */
			lowVariance: RequiredParams<'value'>
			/**
			 * U​I​ ​素​材
			 */
			assetStrip: string
			/**
			 * 点​击​素​材​即​可​在​场​景​图​中​比​对
			 */
			assetStripHint: string
			/**
			 * 导​入​素​材
			 */
			importAssets: string
			/**
			 * 导​入​ ​U​I​ ​素​材
			 */
			importAssetsTitle: string
			/**
			 * 素​材​已​更​新​，​共​ ​{​c​o​u​n​t​}​ ​个
			 * @param {unknown} count
			 */
			imported: RequiredParams<'count'>
			/**
			 * 当​前​脚​本​还​没​有​ ​U​I​ ​素​材
			 */
			noAssets: string
		}
		blockly: {
			/**
			 * 积​木​工​作​区​尚​未​就​绪
			 */
			workspaceNotReady: string
			/**
			 * 工​作​区​必​须​且​只​能​有​一​个​入​口​积​木
			 */
			requireOneStart: string
			/**
			 * 不​支​持​的​积​木​：​{​t​y​p​e​}
			 * @param {unknown} type
			 */
			unsupportedBlock: RequiredParams<'type'>
			/**
			 * 条​件​积​木​不​能​为​空
			 */
			conditionRequired: string
			/**
			 * 新​自​动​化​脚​本
			 */
			defaultWorkflowName: string
			/**
			 * 无​条​件​启​动
			 */
			startUnconditional: string
			/**
			 * 条​件​ ​%​1​ ​满​足​时​就​绪
			 */
			startCondition: string
			/**
			 * 同​时​满​足​ ​%​1​ ​%​2​ ​%​3​ ​%​4
			 */
			conditionAndMany: string
			/**
			 * 任​意​满​足​ ​%​1​ ​%​2​ ​%​3​ ​%​4
			 */
			conditionOrMany: string
			/**
			 * 并​且​/​或​者​积​木​至​少​需​要​连​接​两​个​条​件
			 */
			twoConditionsRequired: string
			/**
			 * 执​行​ ​%​1
			 */
			execute: string
			/**
			 * 识​别​到​ ​%​1​ ​相​似​度​ ​%​2​ ​匹​配​ ​%​3​ ​时​就​绪
			 */
			start: string
			/**
			 * 等​待​图​片​ ​%​1​ ​相​似​度​ ​%​2​ ​匹​配​ ​%​3​ ​超​时​ ​%​4​ ​毫​秒
			 */
			waitImage: string
			/**
			 * 等​待​图​片​ ​%​1​ ​%​2​ ​匹​配​ ​%​3​ ​超​时​ ​%​4​ ​毫​秒
			 */
			waitImageState: string
			/**
			 * 点​击​图​片​ ​%​1​ ​%​2​ ​%​3​ ​次​ ​相​似​度​ ​%​4​ ​匹​配​ ​%​5​ ​点​击​前​确​认​ ​%​6​ ​最​大​移​动​ ​%​7​ ​像​素
			 */
			clickImage: string
			/**
			 * 移​动​到​图​片​ ​%​1​ ​相​似​度​ ​%​2​ ​匹​配​ ​%​3
			 */
			moveToImage: string
			/**
			 * 等​待​ ​%​1​ ​毫​秒
			 */
			delay: string
			/**
			 * 按​键​ ​%​1
			 */
			keyPress: string
			/**
			 * 组​合​键​ ​C​t​r​l​ ​%​1​ ​A​l​t​ ​%​2​ ​S​h​i​f​t​ ​%​3​ ​W​i​n​ ​%​4​ ​+​ ​%​5
			 */
			keyCombo: string
			/**
			 * 按​住​ ​%​1​ ​直​到​图​片​ ​%​2​ ​%​3​ ​匹​配​ ​%​4​ ​超​时​ ​%​5​ ​毫​秒
			 */
			holdKeyUntilImage: string
			/**
			 * 输​入​文​本​ ​%​1​ ​间​隔​ ​%​2​ ​毫​秒
			 */
			textInput: string
			/**
			 * 滚​轮​ ​横​向​ ​%​1​ ​纵​向​ ​%​2
			 */
			scroll: string
			/**
			 * 打​开​网​址​ ​%​1
			 */
			navigate: string
			/**
			 * 刷​新​当​前​页​面
			 */
			reload: string
			/**
			 * 记​录​日​志​ ​%​1
			 */
			log: string
			/**
			 * 如​果​ ​%​1​ ​图​片​ ​%​2​ ​相​似​度​ ​%​3​ ​匹​配​ ​%​4
			 */
			ifImage: string
			/**
			 * 如​果​条​件​ ​%​1
			 */
			ifCondition: string
			/**
			 * 图​片​ ​%​1​ ​相​似​度​ ​%​2​ ​匹​配​ ​%​3
			 */
			imageCondition: string
			/**
			 * %​1​ ​并​且​ ​%​2
			 */
			conditionAnd: string
			/**
			 * %​1​ ​或​者​ ​%​2
			 */
			conditionOr: string
			/**
			 * 不​满​足​ ​%​1
			 */
			conditionNot: string
			/**
			 * 等​待​直​到​条​件​ ​%​1​ ​超​时​ ​%​2​ ​毫​秒
			 */
			waitCondition: string
			/**
			 * 那​么​ ​%​1
			 */
			then: string
			/**
			 * 否​则​ ​%​1
			 */
			otherwise: string
			/**
			 * 重​复​ ​%​1​ ​次
			 */
			repeat: string
			/**
			 * 重​复​直​到​图​片​ ​%​1​ ​%​2​ ​匹​配​ ​%​3​ ​最​多​ ​%​4​ ​次
			 */
			repeatUntilImage: string
			/**
			 * 重​复​直​到​条​件​ ​%​1​ ​最​多​ ​%​2​ ​次
			 */
			repeatUntilCondition: string
			/**
			 * 出​现
			 */
			visible: string
			/**
			 * 消​失
			 */
			hidden: string
			/**
			 * 左​键
			 */
			leftButton: string
			/**
			 * 右​键
			 */
			rightButton: string
			/**
			 * 中​键
			 */
			middleButton: string
			/**
			 * 自​动​遮​罩
			 */
			maskAuto: string
			/**
			 * 透​明​遮​罩
			 */
			maskAlpha: string
			/**
			 * 完​整​图​片
			 */
			maskFull: string
			/**
			 * 识​别​到
			 */
			found: string
			/**
			 * 未​识​别​到
			 */
			notFound: string
			/**
			 * 执​行​到​这​里
			 */
			logSample: string
			/**
			 * 你​好
			 */
			textSample: string
			/**
			 * 入​口
			 */
			catEntry: string
			/**
			 * 图​像
			 */
			catImage: string
			/**
			 * 输​入
			 */
			catInput: string
			/**
			 * 页​面
			 */
			catPage: string
			/**
			 * 流​程
			 */
			catFlow: string
			/**
			 * 调​试
			 */
			catDebug: string
		}
		service: {
			state: {
				/**
				 * 出​现
				 */
				visible: string
				/**
				 * 消​失
				 */
				hidden: string
			}
			status: {
				/**
				 * 测​试​素​材​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				checkingAsset: RequiredParams<'asset'>
				/**
				 * 素​材​匹​配​成​功​，​分​数​ ​{​s​c​o​r​e​}​%
				 * @param {unknown} score
				 */
				assetMatch: RequiredParams<'score'>
				/**
				 * 未​识​别​到​素​材​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				assetNoMatch: RequiredParams<'asset'>
				/**
				 * 就​绪​检​查​失​败​：​{​d​e​t​a​i​l​}
				 * @param {unknown} detail
				 */
				readyCheckFailed: RequiredParams<'detail'>
				/**
				 * 执​行​失​败​：​{​d​e​t​a​i​l​}
				 * @param {unknown} detail
				 */
				runFailed: RequiredParams<'detail'>
				/**
				 * 素​材​测​试​已​停​止​：​{​d​e​t​a​i​l​}
				 * @param {unknown} detail
				 */
				assetTestStopped: RequiredParams<'detail'>
				/**
				 * 素​材​测​试​失​败​：​{​d​e​t​a​i​l​}
				 * @param {unknown} detail
				 */
				assetTestFailed: RequiredParams<'detail'>
				/**
				 * 正​在​执​行​下​一​步
				 */
				stepNext: string
				/**
				 * 脚​本​执​行​完​成
				 */
				scriptCompleted: string
				/**
				 * 脚​本​已​停​止
				 */
				scriptStopped: string
				/**
				 * 识​别​到​ ​{​a​s​s​e​t​}​ ​·​ ​{​s​c​o​r​e​}​%​ ​·​ ​{​m​s​}​m​s
				 * @param {unknown} asset
				 * @param {unknown} ms
				 * @param {unknown} score
				 */
				imageMatch: RequiredParams<'asset' | 'ms' | 'score'>
				/**
				 * 已​暂​停​，​下​一​步​：​{​s​t​e​p​}
				 * @param {unknown} step
				 */
				pausedNext: RequiredParams<'step'>
			}
			step: {
				/**
				 * 执​行​流​程
				 */
				sequence: string
				/**
				 * 等​待​图​片​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				waitImage: RequiredParams<'asset'>
				/**
				 * 等​待​图​片​{​s​t​a​t​e​}​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 * @param {unknown} state
				 */
				waitImageState: RequiredParams<'asset' | 'state'>
				/**
				 * 点​击​图​片​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				clickImage: RequiredParams<'asset'>
				/**
				 * 移​动​到​图​片​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				moveToImage: RequiredParams<'asset'>
				/**
				 * 等​待​ ​{​m​s​}​ ​毫​秒
				 * @param {unknown} ms
				 */
				delay: RequiredParams<'ms'>
				/**
				 * 按​键​ ​{​k​e​y​}
				 * @param {unknown} key
				 */
				keyPress: RequiredParams<'key'>
				/**
				 * 按​住​ ​{​k​e​y​}​ ​直​到​图​片​{​s​t​a​t​e​}​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 * @param {unknown} key
				 * @param {unknown} state
				 */
				keyHoldUntilImage: RequiredParams<'asset' | 'key' | 'state'>
				/**
				 * 输​入​文​本
				 */
				textInput: string
				/**
				 * 滚​动​页​面
				 */
				scroll: string
				/**
				 * 打​开​网​页
				 */
				navigate: string
				/**
				 * 刷​新​页​面
				 */
				reload: string
				/**
				 * 日​志​ ​{​m​e​s​s​a​g​e​}
				 * @param {unknown} message
				 */
				log: RequiredParams<'message'>
				/**
				 * 判​断​图​片​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				ifImage: RequiredParams<'asset'>
				/**
				 * 判​断​组​合​条​件
				 */
				ifCondition: string
				/**
				 * 等​待​组​合​条​件
				 */
				waitCondition: string
				/**
				 * 重​复​ ​{​t​i​m​e​s​}​ ​次
				 * @param {unknown} times
				 */
				repeat: RequiredParams<'times'>
				/**
				 * 重​复​直​到​ ​{​a​s​s​e​t​}
				 * @param {unknown} asset
				 */
				repeatUntilImage: RequiredParams<'asset'>
				/**
				 * 重​复​直​到​组​合​条​件
				 */
				repeatUntilCondition: string
			}
		}
		ipc: {
			/**
			 * 打​开​自​动​化​脚​本​包
			 */
			openPackageTitle: string
			/**
			 * B​a​o​F​l​a​s​h​ ​自​动​化​脚​本
			 */
			openPackageFilter: string
			/**
			 * 替​换
			 */
			replace: string
			/**
			 * 脚​本​已​经​存​在
			 */
			packageExistsTitle: string
			/**
			 * 脚​本​库​中​已​有​相​同​ ​I​D​ ​的​脚​本​，​是​否​使​用​导​入​文​件​替​换​？
			 */
			packageExistsMessage: string
			/**
			 * 替​换​素​材​ ​{​a​s​s​e​t​}
			 * @param {unknown} asset
			 */
			replaceAssetTitle: RequiredParams<'asset'>
			/**
			 * 图​片​素​材
			 */
			imageAssetFilter: string
			/**
			 * 选​择​素​材​目​录
			 */
			selectAssetDir: string
			/**
			 * 导​出​自​动​化​脚​本​包
			 */
			exportPackageTitle: string
		}
	}
	error: {
		/**
		 * 出​错​了
		 */
		title: string
		/**
		 * 组​件​渲​染​异​常
		 */
		'default': string
		/**
		 * D​N​S​ ​解​析​失​败
		 */
		dnsFail: string
		/**
		 * 页​面​加​载​失​败
		 */
		pageLoadFail: string
		/**
		 * 页​面​崩​溃​了
		 */
		pageCrashed: string
	}
}

export type TranslationFunctions = {
	/**
	 * 确定
	 */
	ok: () => LocalizedString
	/**
	 * 取消
	 */
	cancel: () => LocalizedString
	/**
	 * 重试
	 */
	retry: () => LocalizedString
	/**
	 * 加载中...
	 */
	loading: () => LocalizedString
	/**
	 * 确认
	 */
	confirm: () => LocalizedString
	/**
	 * 后退
	 */
	back: () => LocalizedString
	/**
	 * 前进
	 */
	forward: () => LocalizedString
	/**
	 * 刷新
	 */
	refresh: () => LocalizedString
	/**
	 * 停止
	 */
	stop: () => LocalizedString
	/**
	 * 关闭
	 */
	close: () => LocalizedString
	/**
	 * 保存
	 */
	save: () => LocalizedString
	/**
	 * 删除
	 */
	'delete': () => LocalizedString
	/**
	 * 清空
	 */
	clear: () => LocalizedString
	/**
	 * 重置
	 */
	reset: () => LocalizedString
	/**
	 * 复制
	 */
	copy: () => LocalizedString
	/**
	 * 搜索
	 */
	search: () => LocalizedString
	/**
	 * 无
	 */
	none: () => LocalizedString
	/**
	 * 默认
	 */
	'default': () => LocalizedString
	/**
	 * 已启用
	 */
	enabled: () => LocalizedString
	/**
	 * 已禁用
	 */
	disabled: () => LocalizedString
	win: {
		/**
		 * 最小化
		 */
		minimize: () => LocalizedString
		/**
		 * 最大化
		 */
		maximize: () => LocalizedString
		/**
		 * 还原
		 */
		restore: () => LocalizedString
		/**
		 * 关闭
		 */
		close: () => LocalizedString
	}
	tab: {
		/**
		 * 新标签页
		 */
		newTab: () => LocalizedString
		/**
		 * 用户脚本
		 */
		userscripts: () => LocalizedString
		/**
		 * 自动化工作台
		 */
		automation: () => LocalizedString
		/**
		 * 关闭标签页
		 */
		closeTab: () => LocalizedString
		/**
		 * 新标签页 (Ctrl+T)
		 */
		newTabHint: () => LocalizedString
	}
	session: {
		/**
		 * 浏览器上次未正常关闭，是否恢复 {count} 个标签页？
		 */
		restorePrompt: (arg: { count: unknown }) => LocalizedString
		/**
		 * 恢复
		 */
		restore: () => LocalizedString
		/**
		 * 忽略
		 */
		ignore: () => LocalizedString
		/**
		 * 标签页恢复失败，已打开新的标签页
		 */
		restoreFailed: () => LocalizedString
	}
	sidebar: {
		/**
		 * 收藏夹
		 */
		favorites: () => LocalizedString
		/**
		 * 历史记录
		 */
		history: () => LocalizedString
		/**
		 * 下载
		 */
		downloads: () => LocalizedString
		/**
		 * 密码
		 */
		passwords: () => LocalizedString
		/**
		 * 用户脚本
		 */
		userscripts: () => LocalizedString
		/**
		 * 自动化
		 */
		automation: () => LocalizedString
		/**
		 * 设置
		 */
		settings: () => LocalizedString
		/**
		 * 展开侧边栏
		 */
		expand: () => LocalizedString
		/**
		 * 折叠侧边栏
		 */
		collapse: () => LocalizedString
	}
	addressbar: {
		/**
		 * 输入网址或搜索...
		 */
		placeholder: () => LocalizedString
		/**
		 * 取消收藏
		 */
		bookmarkRemove: () => LocalizedString
		/**
		 * 收藏当前页
		 */
		bookmarkAdd: () => LocalizedString
		/**
		 * 静音
		 */
		mute: () => LocalizedString
		/**
		 * 取消静音
		 */
		unmute: () => LocalizedString
		/**
		 * 缩小 (Ctrl+-)
		 */
		zoomOut: () => LocalizedString
		/**
		 * 放大 (Ctrl++)
		 */
		zoomIn: () => LocalizedString
		/**
		 * 点击重置为100%
		 */
		zoomReset: () => LocalizedString
	}
	ruffle: {
		/**
		 * Flash 模式
		 */
		flashMode: () => LocalizedString
		/**
		 * Ruffle 模式
		 */
		ruffleMode: () => LocalizedString
		/**
		 * Flash 模式 — 点击切换 Ruffle
		 */
		switchToRuffle: () => LocalizedString
		/**
		 * Ruffle 模式 — 点击切换 Flash
		 */
		switchToFlash: () => LocalizedString
		/**
		 * Flash
		 */
		flash: () => LocalizedString
		/**
		 * Ruffle
		 */
		ruffle: () => LocalizedString
		/**
		 * Ruffle 加载失败：{detail}
		 */
		loadFailed: (arg: { detail: unknown }) => LocalizedString
		/**
		 * 切回内置版并重试
		 */
		retryBundled: () => LocalizedString
	}
	favorites: {
		/**
		 * ★ 已收藏（点击取消）
		 */
		bookmarkRemove: () => LocalizedString
		/**
		 * ☆ 添加当前页
		 */
		bookmarkAdd: () => LocalizedString
		/**
		 * 暂无收藏
		 */
		empty: () => LocalizedString
	}
	history: {
		/**
		 * 今天
		 */
		today: () => LocalizedString
		/**
		 * 昨天
		 */
		yesterday: () => LocalizedString
		/**
		 * 本周
		 */
		thisWeek: () => LocalizedString
		/**
		 * 更早
		 */
		earlier: () => LocalizedString
		/**
		 * 搜索历史记录
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * 清空
		 */
		clear: () => LocalizedString
		/**
		 * 清空所有历史记录？
		 */
		clearConfirm: () => LocalizedString
		/**
		 * 暂无历史记录
		 */
		empty: () => LocalizedString
		/**
		 * {count} 次访问
		 */
		visitCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * 历史记录已清空
		 */
		cleared: () => LocalizedString
	}
	download: {
		/**
		 * 下载文件
		 */
		title: () => LocalizedString
		/**
		 * 引擎
		 */
		engine: () => LocalizedString
		/**
		 * 位置
		 */
		location: () => LocalizedString
		/**
		 * 暂无下载
		 */
		empty: () => LocalizedString
		/**
		 * 清除已完成
		 */
		clearCompleted: () => LocalizedString
		/**
		 * 已清除完成的下载
		 */
		cleared: () => LocalizedString
		/**
		 * 下载目录已更改
		 */
		dirChanged: () => LocalizedString
		/**
		 * 选择下载目录
		 */
		selectDir: () => LocalizedString
		/**
		 * {filename} 已删除
		 */
		deleted: (arg: { filename: unknown }) => LocalizedString
		/**
		 * {filename} 删除失败
		 */
		deleteFailed: (arg: { filename: unknown }) => LocalizedString
		/**
		 * 确定删除 "{filename}"？
		 */
		deleteConfirm: (arg: { filename: unknown }) => LocalizedString
		/**
		 * 打开文件
		 */
		openFile: () => LocalizedString
		/**
		 * 打开文件夹
		 */
		openDir: () => LocalizedString
		/**
		 * 移除记录
		 */
		removeRecord: () => LocalizedString
		/**
		 * 暂停下载
		 */
		pause: () => LocalizedString
		/**
		 * 恢复下载
		 */
		resume: () => LocalizedString
		/**
		 * 取消下载
		 */
		cancel: () => LocalizedString
		/**
		 * 已暂停
		 */
		paused: () => LocalizedString
		/**
		 * 已完成
		 */
		complete: () => LocalizedString
		/**
		 * 已取消
		 */
		cancelled: () => LocalizedString
		/**
		 * 已中断
		 */
		interrupted: () => LocalizedString
		/**
		 * 准备中...
		 */
		preparing: () => LocalizedString
		/**
		 * 检测中...
		 */
		detecting: () => LocalizedString
		/**
		 * 就绪
		 */
		ready: () => LocalizedString
		/**
		 * aria2 不可用，已回退
		 */
		aria2Unavailable: () => LocalizedString
		/**
		 * {name} 开始下载
		 */
		started: (arg: { name: unknown }) => LocalizedString
		/**
		 * {name} 下载完成
		 */
		completed: (arg: { name: unknown }) => LocalizedString
		/**
		 * {name} 已取消
		 */
		cancelledNotify: (arg: { name: unknown }) => LocalizedString
		/**
		 * {name} 下载失败
		 */
		failed: (arg: { name: unknown }) => LocalizedString
		/**
		 * 文件
		 */
		file: () => LocalizedString
	}
	password: {
		/**
		 * 尚未设置主密码
		 */
		notSetup: () => LocalizedString
		/**
		 * 设置后可保存和查看密码
		 */
		notSetupDesc: () => LocalizedString
		/**
		 * 设置主密码 (8位, 含大小写+数字)
		 */
		setupPlaceholder: () => LocalizedString
		/**
		 * 确认主密码
		 */
		confirmPlaceholder: () => LocalizedString
		/**
		 * 设置主密码
		 */
		setupBtn: () => LocalizedString
		/**
		 * 两次密码不一致
		 */
		mismatch: () => LocalizedString
		/**
		 * 密码至少 8 位
		 */
		tooShort: () => LocalizedString
		/**
		 * 密码需包含大写、小写和数字
		 */
		complexityFail: () => LocalizedString
		/**
		 * 设置失败
		 */
		setupFailed: () => LocalizedString
		/**
		 * 启用密码本
		 */
		enable: () => LocalizedString
		/**
		 * 输入主密码解锁
		 */
		unlockPlaceholder: () => LocalizedString
		/**
		 * 解锁
		 */
		unlockBtn: () => LocalizedString
		/**
		 * 密码错误
		 */
		wrongPassword: () => LocalizedString
		/**
		 * 锁定
		 */
		lock: () => LocalizedString
		/**
		 * 暂无保存的密码
		 */
		empty: () => LocalizedString
		/**
		 * 隐藏
		 */
		hide: () => LocalizedString
		/**
		 * 查看
		 */
		view: () => LocalizedString
		/**
		 * 设为默认
		 */
		setDefault: () => LocalizedString
		/**
		 * 重置密码本
		 */
		resetBtn: () => LocalizedString
		/**
		 * 确认重置？再次点击确认
		 */
		resetConfirm: () => LocalizedString
		/**
		 * 密码本已重置
		 */
		resetDone: () => LocalizedString
		/**
		 * 重置将清空所有已保存的密码，需重新设置主密码。
		 */
		resetDesc: () => LocalizedString
		/**
		 * 检测到登录信息，可启用密码本保存
		 */
		captureNotify: () => LocalizedString
		/**
		 * 启用密码本
		 */
		enableBtn: () => LocalizedString
		/**
		 * 为 {host} 保存密码？
		 */
		savePrompt: (arg: { host: unknown }) => LocalizedString
		/**
		 * 密码保存失败，请解锁密码本后重试
		 */
		saveFailed: () => LocalizedString
		/**
		 * 忽略
		 */
		ignore: () => LocalizedString
		/**
		 * 已删除
		 */
		deleted: () => LocalizedString
		/**
		 * 自动检测登录信息
		 */
		autoCapture: () => LocalizedString
		/**
		 * 默认开启；关闭后不再向网页附加密码捕获器。
		 */
		autoCaptureHint: () => LocalizedString
		/**
		 * 自动填充保存的密码
		 */
		autoFill: () => LocalizedString
		/**
		 * 密码本锁定时也可填充，但不会自动提交表单。
		 */
		autoFillHint: () => LocalizedString
		/**
		 * 旧密码本需成功解锁一次，之后才能在锁定状态下自动填充。
		 */
		autoFillNeedsUnlock: () => LocalizedString
		/**
		 * 已填充登录信息，请确认后登录
		 */
		filled: () => LocalizedString
		/**
		 * 填充当前页面
		 */
		fill: () => LocalizedString
		/**
		 * 当前页面没有可安全填充的匹配登录表单
		 */
		fillFailed: () => LocalizedString
		/**
		 * 不捕获的网站
		 */
		excludedSites: () => LocalizedString
		/**
		 * 每行填写一个域名，同时排除其子域名。修改后立即对已打开标签生效。
		 */
		excludedSitesHint: () => LocalizedString
		/**
		 * 保存排除列表
		 */
		saveExcludedSites: () => LocalizedString
		/**
		 * 密码捕获排除列表已保存
		 */
		excludedSitesSaved: () => LocalizedString
		/**
		 * 排除列表保存失败
		 */
		excludedSitesSaveFailed: () => LocalizedString
	}
	settings: {
		/**
		 * 设置
		 */
		title: () => LocalizedString
		/**
		 * 设置分类
		 */
		categories: () => LocalizedString
		/**
		 * 设置已保存
		 */
		saved: () => LocalizedString
		/**
		 * 设置保存失败：{error}
		 */
		saveFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * 设置已保存，需重启生效
		 */
		savedRestart: () => LocalizedString
		/**
		 * 保存设置
		 */
		saveBtn: () => LocalizedString
		/**
		 * 已保存 ✓
		 */
		savedBtn: () => LocalizedString
		/**
		 * 已保存 — 需重启生效
		 */
		savedRestartBtn: () => LocalizedString
		/**
		 * 通用
		 */
		general: () => LocalizedString
		/**
		 * 主页地址
		 */
		homepage: () => LocalizedString
		/**
		 * 异常关闭后询问恢复标签
		 */
		restoreSession: () => LocalizedString
		/**
		 * 正常关闭不会恢复；仅在崩溃、断电或强制结束后询问，最多恢复 20 个标签页。
		 */
		restoreSessionHint: () => LocalizedString
		/**
		 * 休眠长期未使用的标签页
		 */
		suspendInactiveTabs: () => LocalizedString
		/**
		 * 可选；非活动且未播放声音的网页标签在 10 分钟后释放进程，切回时自动重新载入。
		 */
		suspendInactiveTabsHint: () => LocalizedString
		/**
		 * 搜索引擎
		 */
		searchEngine: () => LocalizedString
		/**
		 * 百度
		 */
		baidu: () => LocalizedString
		/**
		 * 伪装版本
		 */
		spoofVersion: () => LocalizedString
		/**
		 * 伪装为指定版本号，部分网站会检测。需重启生效。
		 */
		spoofVersionHint: () => LocalizedString
		/**
		 * Flash 插件通道
		 */
		flashPluginChannel: () => LocalizedString
		/**
		 * 稳定通道（推荐）
		 */
		flashPluginStable: () => LocalizedString
		/**
		 * Windows/Linux 使用项目已验证的插件。macOS 没有稳定通道。需重启生效。
		 */
		flashPluginStableHint: () => LocalizedString
		/**
		 * 实验通道
		 */
		flashPluginExperimental: () => LocalizedString
		/**
		 * 包含国内修改版或 macOS PPAPI。可能出现组件错误、弹窗、崩溃或无法启动；macOS 未经任何设备测试。
		 */
		flashPluginExperimentalWarning: () => LocalizedString
		/**
		 * 低性能设备模式
		 */
		lowEndMode: () => LocalizedString
		/**
		 * 需重启生效
		 */
		lowEndModeHint: () => LocalizedString
		/**
		 * Ruffle
		 */
		ruffle: () => LocalizedString
		/**
		 * 新标签默认引擎
		 */
		defaultEngine: () => LocalizedString
		/**
		 * 自动 (PPAPI 优先)
		 */
		ppapiAuto: () => LocalizedString
		/**
		 * Ruffle (WASM 模拟)
		 */
		preferRuffle: () => LocalizedString
		/**
		 * 仅 PPAPI
		 */
		ppapiOnly: () => LocalizedString
		/**
		 * Ruffle 来源
		 */
		ruffleSource: () => LocalizedString
		/**
		 * 自托管 (离线可用)
		 */
		bundled: () => LocalizedString
		/**
		 * CDN (始终最新)
		 */
		cdn: () => LocalizedString
		/**
		 * 仅对新建标签页生效，已有标签页用导航栏按钮切换
		 */
		ruffleHint: () => LocalizedString
		/**
		 * 下载
		 */
		download: () => LocalizedString
		/**
		 * 下载引擎
		 */
		downloadEngine: () => LocalizedString
		/**
		 * aria2 (多连接加速)
		 */
		aria2: () => LocalizedString
		/**
		 * Chromium (内置)
		 */
		chromium: () => LocalizedString
		/**
		 * 外观
		 */
		appearance: () => LocalizedString
		/**
		 * 页面缩放
		 */
		zoom: () => LocalizedString
		/**
		 * 重置
		 */
		zoomReset: () => LocalizedString
		/**
		 * 主题
		 */
		theme: () => LocalizedString
		/**
		 * 切换到亮色
		 */
		themeSwitchToLight: () => LocalizedString
		/**
		 * 切换到暗色
		 */
		themeSwitchToDark: () => LocalizedString
		/**
		 * 跟随系统
		 */
		system: () => LocalizedString
		/**
		 * 兼容性诊断
		 */
		diagnostics: () => LocalizedString
		/**
		 * 打开本地 SWF 游戏
		 */
		openLocalSwf: () => LocalizedString
		/**
		 * 导出运行环境、组件哈希和最近日志。账号路径、网址参数、口令与令牌会被脱敏。
		 */
		diagnosticsHint: () => LocalizedString
		/**
		 * 导出脱敏诊断报告
		 */
		diagnosticsExport: () => LocalizedString
		/**
		 * 正在生成报告…
		 */
		diagnosticsExporting: () => LocalizedString
		/**
		 * 诊断报告已保存
		 */
		diagnosticsSaved: () => LocalizedString
		/**
		 * 诊断报告导出失败
		 */
		diagnosticsFailed: () => LocalizedString
		/**
		 * 语言
		 */
		language: () => LocalizedString
		userscriptCapacity: {
			/**
			 * 用户脚本容量
			 */
			title: () => LocalizedString
			/**
			 * 保存后立即生效,无需重启。
			 */
			hint: () => LocalizedString
			/**
			 * 请求响应上限 (MB)
			 */
			maxResponseMB: () => LocalizedString
			/**
			 * 请求超时 (秒)
			 */
			timeoutSeconds: () => LocalizedString
			/**
			 * 每脚本并发请求数
			 */
			concurrentPerScript: () => LocalizedString
			/**
			 * 全局并发请求数
			 */
			concurrentGlobal: () => LocalizedString
			/**
			 * 下载单文件上限 (MB)
			 */
			downloadMaxMB: () => LocalizedString
			/**
			 * 下载每脚本并发数
			 */
			downloadConcurrent: () => LocalizedString
			/**
			 * 单值大小上限 (KB,重启生效)
			 */
			maxValueKB: () => LocalizedString
		}
		screenshot: {
			/**
			 * 截图
			 */
			capture: () => LocalizedString
			/**
			 * 截取当前标签页画面并保存
			 */
			captureHint: () => LocalizedString
			/**
			 * 截图已保存
			 */
			captured: () => LocalizedString
			/**
			 * 打开文件夹
			 */
			openFolder: () => LocalizedString
			/**
			 * 截图失败
			 */
			captureFailed: () => LocalizedString
			/**
			 * 截图保存目录
			 */
			dir: () => LocalizedString
			/**
			 * 选择目录
			 */
			selectDir: () => LocalizedString
			/**
			 * 截图目录已更改
			 */
			dirChanged: () => LocalizedString
			/**
			 * 所选目录不可写
			 */
			dirNotWritable: () => LocalizedString
			/**
			 * 所选目录位于程序数据目录内
			 */
			dirDenied: () => LocalizedString
			/**
			 * 选择目录失败
			 */
			dirSelectFailed: () => LocalizedString
			/**
			 * 选择截图保存目录
			 */
			dialogTitle: () => LocalizedString
		}
	}
	find: {
		/**
		 * 查找
		 */
		placeholder: () => LocalizedString
	}
	newtab: {
		/**
		 * 搜索或输入网址
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * 百度
		 */
		baidu: () => LocalizedString
		/**
		 * B站
		 */
		bilibili: () => LocalizedString
	}
	bookmark: {
		/**
		 * 已收藏 {title}
		 */
		added: (arg: { title: unknown }) => LocalizedString
		/**
		 * 已取消收藏 {title}
		 */
		removed: (arg: { title: unknown }) => LocalizedString
	}
	userscript: {
		/**
		 * 用户脚本
		 */
		title: () => LocalizedString
		/**
		 * 搜索名称 / 匹配 / 命名空间
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * 添加新脚本
		 */
		addNew: () => LocalizedString
		/**
		 * 从文件安装
		 */
		installFromFile: () => LocalizedString
		/**
		 * 从 URL 安装
		 */
		installFromUrl: () => LocalizedString
		/**
		 * 输入 .user.js 的 URL 后回车
		 */
		urlPlaceholder: () => LocalizedString
		/**
		 * 粘贴脚本源码
		 */
		pasteSource: () => LocalizedString
		/**
		 * 或在此粘贴脚本源码…
		 */
		pastePlaceholder: () => LocalizedString
		/**
		 * 解析预览
		 */
		parsePreview: () => LocalizedString
		/**
		 * {count} 个脚本
		 */
		scriptCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * 加载中…
		 */
		loading: () => LocalizedString
		/**
		 * 没有匹配的脚本。
		 */
		noMatch: () => LocalizedString
		/**
		 * 尚未安装任何脚本。点击右上角"添加新脚本"开始。
		 */
		empty: () => LocalizedString
		/**
		 * 全部
		 */
		filterAll: () => LocalizedString
		/**
		 * 已启用
		 */
		filterEnabled: () => LocalizedString
		/**
		 * 已禁用
		 */
		filterDisabled: () => LocalizedString
		/**
		 * 启用
		 */
		colEnable: () => LocalizedString
		/**
		 * 脚本
		 */
		colScript: () => LocalizedString
		/**
		 * 状态
		 */
		colStatus: () => LocalizedString
		/**
		 * 匹配
		 */
		colMatch: () => LocalizedString
		/**
		 * 操作
		 */
		colActions: () => LocalizedString
		/**
		 * 运行中
		 */
		statusRunning: () => LocalizedString
		/**
		 * 已禁用
		 */
		statusDisabled: () => LocalizedString
		/**
		 * 全部页面
		 */
		matchAllPages: () => LocalizedString
		/**
		 * 无匹配
		 */
		matchNone: () => LocalizedString
		/**
		 * 授权
		 */
		permission: () => LocalizedString
		/**
		 * 跨域
		 */
		permissionCrossOrigin: () => LocalizedString
		/**
		 * 外部脚本
		 */
		permissionExternalScript: () => LocalizedString
		/**
		 * 资源
		 */
		permissionResources: () => LocalizedString
		/**
		 * 无额外授权
		 */
		permissionNone: () => LocalizedString
		/**
		 * 编辑
		 */
		edit: () => LocalizedString
		/**
		 * 删除
		 */
		'delete': () => LocalizedString
		/**
		 * 启用
		 */
		enable: () => LocalizedString
		/**
		 * 禁用
		 */
		disable: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 安装
		 */
		install: () => LocalizedString
		/**
		 * ← 返回列表
		 */
		backToList: () => LocalizedString
		/**
		 * 编辑：{scriptId}
		 */
		editorTitle: (arg: { scriptId: unknown }) => LocalizedString
		/**
		 * 保存失败：{error}
		 */
		saveFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * 已保存
		 */
		saveSuccess: () => LocalizedString
		/**
		 * 脚本有未保存的修改，确定离开吗？
		 */
		dirtyConfirm: () => LocalizedString
		/**
		 * 安装确认
		 */
		installConfirm: () => LocalizedString
		/**
		 * 来源：{from}
		 */
		installSource: (arg: { from: unknown }) => LocalizedString
		/**
		 * 待安装
		 */
		installBadge: () => LocalizedString
		/**
		 * 匹配范围
		 */
		installMatchScope: () => LocalizedString
		/**
		 * 安装后脚本将按上述匹配范围在所有标签页执行。请确认来源可信。
		 */
		installWarning: () => LocalizedString
		/**
		 * 已安装「{name}」
		 */
		installSuccess: (arg: { name: unknown }) => LocalizedString
		/**
		 * 本地文件
		 */
		installLocalFile: () => LocalizedString
		/**
		 * 安装用户脚本
		 */
		installFileDialogTitle: () => LocalizedString
		/**
		 * 导出脚本
		 */
		exportDialogTitle: () => LocalizedString
		/**
		 * 删除脚本「{name}」？
		 */
		deleteConfirm: (arg: { name: unknown }) => LocalizedString
		/**
		 * 已删除「{name}」
		 */
		deleteSuccess: (arg: { name: unknown }) => LocalizedString
		/**
		 * 读取文件失败：{error}
		 */
		fileReadFailed: (arg: { error: unknown }) => LocalizedString
		/**
		 * 下载失败：{error}
		 */
		downloadFailed: (arg: { error: unknown }) => LocalizedString
		panel: {
			/**
			 * 当前页面匹配
			 */
			matchedOnPage: () => LocalizedString
			/**
			 * 管理所有脚本
			 */
			manageAll: () => LocalizedString
			/**
			 * 当前页面没有匹配的脚本。
			 */
			noMatchOnPage: () => LocalizedString
			/**
			 * 命令已发送到页面
			 */
			commandSent: () => LocalizedString
			/**
			 * 命令执行失败(脚本可能已卸载或页面已刷新)
			 */
			commandFailed: () => LocalizedString
			/**
			 * 命令执行失败
			 */
			commandFailedSimple: () => LocalizedString
			/**
			 * 脚本命令
			 */
			commands: () => LocalizedString
			/**
			 * 执行中…
			 */
			commandRunning: () => LocalizedString
		}
		update: {
			/**
			 * 检查更新
			 */
			checkButton: () => LocalizedString
			/**
			 * 检查中…
			 */
			checking: () => LocalizedString
			/**
			 * 发现 {count} 个可更新脚本
			 */
			found: (arg: { count: unknown }) => LocalizedString
			/**
			 * 所有脚本都是最新版本
			 */
			none: () => LocalizedString
			/**
			 * 更新到 v{version}
			 */
			latest: (arg: { version: unknown }) => LocalizedString
			/**
			 * 已编辑
			 */
			edited: () => LocalizedString
			/**
			 * 弱安全更新源
			 */
			weakSource: () => LocalizedString
			/**
			 * 该脚本的更新源仅经 @match 域名校验,应用更新将覆盖你的改动,确定继续?
			 */
			weakConfirm: () => LocalizedString
			/**
			 * 已更新「{name}」到 v{version}
			 */
			success: (arg: { name: unknown, version: unknown }) => LocalizedString
			/**
			 * 更新失败:{error}
			 */
			failed: (arg: { error: unknown }) => LocalizedString
			/**
			 * 更新服务繁忙,请稍后再试
			 */
			rateLimit: () => LocalizedString
		}
		/**
		 * 导出
		 */
		'export': () => LocalizedString
		/**
		 * 已导出到 {path}
		 */
		exported: (arg: { path: unknown }) => LocalizedString
		/**
		 * 导出失败:{error}
		 */
		exportFailed: (arg: { error: unknown }) => LocalizedString
		values: {
			/**
			 * 查看/编辑值
			 */
			open: () => LocalizedString
			/**
			 * 脚本值
			 */
			title: () => LocalizedString
			/**
			 * 该脚本暂无 GM 值。
			 */
			empty: () => LocalizedString
			/**
			 * 读取值失败
			 */
			loadFailed: () => LocalizedString
			/**
			 * 编辑
			 */
			edit: () => LocalizedString
			/**
			 * 删除
			 */
			'delete': () => LocalizedString
			/**
			 * 保存
			 */
			save: () => LocalizedString
			/**
			 * 取消
			 */
			cancel: () => LocalizedString
			/**
			 * 值必须是合法 JSON
			 */
			invalid: () => LocalizedString
			/**
			 * 保存失败(超出大小上限或非法值)
			 */
			saveFailed: () => LocalizedString
		}
		background: {
			/**
			 * 后台
			 */
			badge: () => LocalizedString
			/**
			 * 后台脚本已停止:{scripts}
			 */
			stoppedScripts: (arg: { scripts: unknown }) => LocalizedString
			/**
			 * 重启全部后台脚本
			 */
			restart: () => LocalizedString
			/**
			 * 重启
			 */
			restartScript: () => LocalizedString
			/**
			 * 或一次性重启全部后台脚本:
			 */
			restartAllHint: () => LocalizedString
		}
	}
	automation: {
		page: {
			/**
			 * 自动化工作台
			 */
			title: () => LocalizedString
			/**
			 * 搭建脚本、管理识别素材，并在目标网页的自动化侧栏中运行。
			 */
			subtitle: () => LocalizedString
			/**
			 * 正在加载自动化工作台…
			 */
			loading: () => LocalizedString
			/**
			 * 新建脚本
			 */
			newScript: () => LocalizedString
			/**
			 * 导入 .baoauto
			 */
			importPackage: () => LocalizedString
			/**
			 * 导出脚本包
			 */
			exportPackage: () => LocalizedString
			/**
			 * 保存修改
			 */
			saveChanges: () => LocalizedString
			/**
			 * 当前版本可以创建和编辑脚本；网页识别与执行仍处于实验开关关闭状态。
			 */
			warningDisabled: () => LocalizedString
			/**
			 * 脚本库
			 */
			libraryTitle: () => LocalizedString
			/**
			 * {count} 个素材
			 */
			assetCount: (arg: { count: unknown }) => LocalizedString
			/**
			 * 个素材
			 */
			assetCountLabel: () => LocalizedString
			/**
			 * 复制脚本
			 */
			duplicateTitle: () => LocalizedString
			/**
			 * 删除脚本
			 */
			deleteTitle: () => LocalizedString
			/**
			 * 还没有脚本
			 */
			emptyLibrary: () => LocalizedString
			/**
			 * 新建脚本或导入工作台导出的 `.baoauto` 文件。
			 */
			emptyLibraryHint: () => LocalizedString
			/**
			 * 识别素材
			 */
			assetsTitle: () => LocalizedString
			/**
			 * 合并素材目录
			 */
			mergeAssetsTitle: () => LocalizedString
			/**
			 * 添加
			 */
			add: () => LocalizedString
			/**
			 * 这个脚本尚未包含图片素材。
			 */
			noAssetsHint: () => LocalizedString
			/**
			 * 正在被脚本引用，不能删除
			 */
			assetReferenced: () => LocalizedString
			/**
			 * 当前未被脚本引用
			 */
			assetUnreferenced: () => LocalizedString
			/**
			 * 替换
			 */
			replace: () => LocalizedString
			/**
			 * 删除素材
			 */
			deleteAssetTitle: () => LocalizedString
			/**
			 * 请先从积木中移除该素材引用
			 */
			removeAssetReferenceHint: () => LocalizedString
			/**
			 * 脚本名称
			 */
			name: () => LocalizedString
			/**
			 * 脚本 ID
			 */
			id: () => LocalizedString
			/**
			 * 说明
			 */
			description: () => LocalizedString
			/**
			 * 积木编辑
			 */
			blocksTab: () => LocalizedString
			/**
			 * JSON 代码
			 */
			jsonTab: () => LocalizedString
			/**
			 * 素材测试台
			 */
			testBenchTab: () => LocalizedString
			/**
			 * 校验并应用 JSON
			 */
			applyJson: () => LocalizedString
			/**
			 * 选择或导入一个脚本
			 */
			emptyEditorTitle: () => LocalizedString
			/**
			 * 脚本会显示在左侧脚本库中。
			 */
			emptyEditorHint: () => LocalizedString
			/**
			 * 新建自动化脚本
			 */
			createDialogTitle: () => LocalizedString
			/**
			 * 复制自动化脚本
			 */
			duplicateDialogTitle: () => LocalizedString
			/**
			 * 脚本 ID 将用于文件名，创建后不能直接修改。
			 */
			dialogIdHint: () => LocalizedString
			/**
			 * 正在创建…
			 */
			creating: () => LocalizedString
			/**
			 * 创建脚本
			 */
			create: () => LocalizedString
			/**
			 * 取消
			 */
			cancel: () => LocalizedString
			/**
			 * 已导入 {name}
			 */
			noticeImported: (arg: { name: unknown }) => LocalizedString
			/**
			 * 新脚本已创建并持久保存
			 */
			noticeCreated: () => LocalizedString
			/**
			 * 脚本副本已创建
			 */
			noticeDuplicated: () => LocalizedString
			/**
			 * 脚本已删除
			 */
			noticeDeleted: () => LocalizedString
			/**
			 * 素材目录已合并，共 {count} 个素材
			 */
			noticeMerged: (arg: { count: unknown }) => LocalizedString
			/**
			 * 素材 {asset} 已替换
			 */
			noticeReplaced: (arg: { asset: unknown }) => LocalizedString
			/**
			 * 素材 {asset} 已删除
			 */
			noticeAssetDeleted: (arg: { asset: unknown }) => LocalizedString
			/**
			 * 脚本已载入
			 */
			noticeLoaded: () => LocalizedString
			/**
			 * 积木修改已保存到当前脚本包
			 */
			noticeSaved: () => LocalizedString
			/**
			 * 搜索素材或目录
			 */
			searchAssets: () => LocalizedString
			/**
			 * 根目录
			 */
			rootFolder: () => LocalizedString
			/**
			 * 关联目录
			 */
			linkFolder: () => LocalizedString
			/**
			 * 同步
			 */
			syncFolder: () => LocalizedString
			/**
			 * 选择要关联的素材目录
			 */
			linkFolderTitle: () => LocalizedString
			/**
			 * 已关联 {name}，发现 {count} 个素材
			 */
			folderLinked: (arg: { count: unknown, name: unknown }) => LocalizedString
			/**
			 * 同步完成：新增或更新 {changed} 个，目录中缺少 {missing} 个（未自动删除）
			 */
			folderSynced: (arg: { changed: unknown, missing: unknown }) => LocalizedString
			/**
			 * 自动图片组 {count} 个
			 */
			imageGroups: (arg: { count: unknown }) => LocalizedString
			/**
			 * 同一子目录中至少两张图片会组成图片组，可在识图积木中直接选择。
			 */
			imageGroupsHint: () => LocalizedString
			/**
			 * 检查脚本包
			 */
			diagnose: () => LocalizedString
			/**
			 * 脚本包检查通过
			 */
			diagnosticPassed: () => LocalizedString
			/**
			 * 脚本包存在阻塞问题
			 */
			diagnosticFailed: () => LocalizedString
			/**
			 * {steps} 个步骤 · 深度 {depth} · {assets} 个素材 · {size} MB
			 */
			diagnosticMetrics: (arg: { assets: unknown, depth: unknown, size: unknown, steps: unknown }) => LocalizedString
			/**
			 * 有未保存修改，草稿已自动保存在本机
			 */
			unsaved: () => LocalizedString
			/**
			 * 保存修改 *
			 */
			saveDirty: () => LocalizedString
			/**
			 * 当前脚本有未保存修改，仍要切换脚本吗？本机草稿会保留。
			 */
			unsavedConfirm: () => LocalizedString
			/**
			 * JSON 已校验并同步到积木
			 */
			noticeJsonApplied: () => LocalizedString
			/**
			 * 已导出到 {path}
			 */
			noticeExported: (arg: { path: unknown }) => LocalizedString
			/**
			 * 所选位置
			 */
			noticeFallbackPath: () => LocalizedString
			/**
			 * 导入脚本包或新建脚本后即可编辑
			 */
			noticeInitial: () => LocalizedString
			/**
			 * 确定删除"{name}"吗？此操作会删除已安装的脚本包。
			 */
			deletePackageConfirm: (arg: { name: unknown }) => LocalizedString
			/**
			 * 确定删除素材"{asset}"吗？
			 */
			deleteAssetConfirm: (arg: { asset: unknown }) => LocalizedString
			/**
			 * 新自动化脚本
			 */
			draftDefaultName: () => LocalizedString
			/**
			 * {name} 副本
			 */
			copySuffix: (arg: { name: unknown }) => LocalizedString
		}
		panel: {
			/**
			 * 打开自动化工作台
			 */
			openWorkbench: () => LocalizedString
			/**
			 * 当前版本尚未启用自动化执行能力。
			 */
			notEnabled: () => LocalizedString
			/**
			 * 脚本
			 */
			scripts: () => LocalizedString
			/**
			 * 导入
			 */
			'import': () => LocalizedString
			/**
			 * 先导入一个 `.baoauto` 脚本包
			 */
			emptyPackage: () => LocalizedString
			/**
			 * {count} 个识别素材 · {id}
			 */
			assetMeta: (arg: { count: unknown, id: unknown }) => LocalizedString
			/**
			 * 第 {count} 步 · {step}
			 */
			currentStep: (arg: { count: unknown, step: unknown }) => LocalizedString
			/**
			 * 当前网页可作为执行目标
			 */
			webTargetHint: () => LocalizedString
			/**
			 * 请切换到要操作的网页
			 */
			switchTargetHint: () => LocalizedString
			/**
			 * 从当前网页截取素材
			 */
			captureAsset: () => LocalizedString
			/**
			 * 拖动框选识别区域
			 */
			dragToSelect: () => LocalizedString
			/**
			 * 当前网页截图
			 */
			captureAlt: () => LocalizedString
			/**
			 * 已选 {w} × {h}
			 */
			selectedRect: (arg: { h: unknown, w: unknown }) => LocalizedString
			/**
			 * 按住鼠标拖动框选
			 */
			dragHint: () => LocalizedString
			/**
			 * 保存为脚本素材
			 */
			saveAsAsset: () => LocalizedString
			/**
			 * captures/button.png
			 */
			assetNamePlaceholder: () => LocalizedString
			/**
			 * 素材识别测试
			 */
			assetTestTitle: () => LocalizedString
			/**
			 * 识别阈值
			 */
			thresholdAria: () => LocalizedString
			/**
			 * 在当前网页测试
			 */
			testOnPage: () => LocalizedString
			/**
			 * 匹配 {score}% · 位置 {x}, {y} · {w} × {h}{ms}
			 */
			matchResult: (arg: { h: unknown, ms: unknown, score: unknown, w: unknown, x: unknown, y: unknown }) => LocalizedString
			/**
			 *  · {ms}ms
			 */
			matchResultMs: (arg: { ms: unknown }) => LocalizedString
			/**
			 * 未达到当前阈值，请检查素材或降低阈值。
			 */
			matchFail: () => LocalizedString
			/**
			 * 单步启动
			 */
			debugStart: () => LocalizedString
			/**
			 * 下一步
			 */
			debugNext: () => LocalizedString
			/**
			 * 运行日志
			 */
			runLog: () => LocalizedString
			/**
			 * 历史运行
			 */
			runHistory: () => LocalizedString
			/**
			 * 尚无已完成的正式运行或单步调试记录。
			 */
			historyEmpty: () => LocalizedString
			/**
			 * 运行
			 */
			historyRun: () => LocalizedString
			/**
			 * 调试
			 */
			historyDebug: () => LocalizedString
			/**
			 * {state} · {steps} 步 · {seconds} 秒
			 */
			historyRecord: (arg: { seconds: unknown, state: unknown, steps: unknown }) => LocalizedString
			/**
			 * 清除此脚本历史
			 */
			clearHistory: () => LocalizedString
			/**
			 * 运行或单步调试后，步骤和错误会显示在这里。
			 */
			logEmpty: () => LocalizedString
			/**
			 * 检查就绪
			 */
			checkReady: () => LocalizedString
			/**
			 * 3 秒启动
			 */
			countdownStart: () => LocalizedString
			/**
			 * 立即启动
			 */
			startNow: () => LocalizedString
			/**
			 * 停止
			 */
			stop: () => LocalizedString
			/**
			 * 素材"{asset}"已经存在，是否替换？
			 */
			replaceAssetConfirm: (arg: { asset: unknown }) => LocalizedString
			/**
			 * 已保存素材 {asset}（{w} × {h}）
			 */
			assetSaved: (arg: { asset: unknown, h: unknown, w: unknown }) => LocalizedString
			status: {
				/**
				 * 等待检查
				 */
				idle: () => LocalizedString
				/**
				 * 正在识别
				 */
				checking: () => LocalizedString
				/**
				 * 已经就绪
				 */
				ready: () => LocalizedString
				/**
				 * 倒计时中
				 */
				countdown: () => LocalizedString
				/**
				 * 正在执行
				 */
				running: () => LocalizedString
				/**
				 * 执行完成
				 */
				completed: () => LocalizedString
				/**
				 * 执行失败
				 */
				failed: () => LocalizedString
				/**
				 * 已停止
				 */
				cancelled: () => LocalizedString
			}
		}
		testBench: {
			/**
			 * UI 素材匹配测试台
			 */
			title: () => LocalizedString
			/**
			 * 在指定场景图中定位 UI 素材
			 */
			subtitle: () => LocalizedString
			/**
			 * 阈值 {value}%
			 */
			threshold: (arg: { value: unknown }) => LocalizedString
			/**
			 * 多尺度
			 */
			multiScale: () => LocalizedString
			/**
			 * 最小
			 */
			scaleMin: () => LocalizedString
			/**
			 * 最大
			 */
			scaleMax: () => LocalizedString
			/**
			 * 步长
			 */
			scaleStep: () => LocalizedString
			/**
			 * 匹配模式
			 */
			maskMode: () => LocalizedString
			/**
			 * 自动遮罩
			 */
			maskAuto: () => LocalizedString
			/**
			 * 透明遮罩
			 */
			alphaMask: () => LocalizedString
			/**
			 * 完整图片
			 */
			maskFull: () => LocalizedString
			/**
			 * 开始比对
			 */
			compare: () => LocalizedString
			/**
			 * 比对中
			 */
			comparing: () => LocalizedString
			/**
			 * 选择目标场景图片
			 */
			openSceneTitle: () => LocalizedString
			/**
			 * 图片文件
			 */
			imageFilter: () => LocalizedString
			/**
			 * 导入目标场景图
			 */
			importScene: () => LocalizedString
			/**
			 * 这张图片将占据测试台主要区域
			 */
			importSceneHint: () => LocalizedString
			/**
			 * 更换场景图
			 */
			replaceScene: () => LocalizedString
			/**
			 * 缩小场景图
			 */
			zoomOut: () => LocalizedString
			/**
			 * 放大场景图
			 */
			zoomIn: () => LocalizedString
			/**
			 * 适应场景区域
			 */
			fitScene: () => LocalizedString
			/**
			 * 专注查看场景图
			 */
			focusScene: () => LocalizedString
			/**
			 * 退出专注查看
			 */
			exitFocus: () => LocalizedString
			/**
			 * 匹配成功
			 */
			matched: () => LocalizedString
			/**
			 * 最佳候选低于阈值
			 */
			belowThreshold: () => LocalizedString
			/**
			 * 没有可用的匹配候选
			 */
			noCandidate: () => LocalizedString
			/**
			 * 导入场景图并选择下方素材开始测试
			 */
			waiting: () => LocalizedString
			/**
			 * 匹配度 {score}% · 坐标 ({x}, {y}) · {width}×{height} · 缩放 {scale} · {ms}ms
			 */
			metrics: (arg: { height: unknown, ms: unknown, scale: unknown, score: unknown, width: unknown, x: unknown, y: unknown }) => LocalizedString
			/**
			 * 素材对比度很低（标准差 {value}），已切换纯色匹配模式；建议裁入更多边缘特征。
			 */
			lowVariance: (arg: { value: unknown }) => LocalizedString
			/**
			 * UI 素材
			 */
			assetStrip: () => LocalizedString
			/**
			 * 点击素材即可在场景图中比对
			 */
			assetStripHint: () => LocalizedString
			/**
			 * 导入素材
			 */
			importAssets: () => LocalizedString
			/**
			 * 导入 UI 素材
			 */
			importAssetsTitle: () => LocalizedString
			/**
			 * 素材已更新，共 {count} 个
			 */
			imported: (arg: { count: unknown }) => LocalizedString
			/**
			 * 当前脚本还没有 UI 素材
			 */
			noAssets: () => LocalizedString
		}
		blockly: {
			/**
			 * 积木工作区尚未就绪
			 */
			workspaceNotReady: () => LocalizedString
			/**
			 * 工作区必须且只能有一个入口积木
			 */
			requireOneStart: () => LocalizedString
			/**
			 * 不支持的积木：{type}
			 */
			unsupportedBlock: (arg: { type: unknown }) => LocalizedString
			/**
			 * 条件积木不能为空
			 */
			conditionRequired: () => LocalizedString
			/**
			 * 新自动化脚本
			 */
			defaultWorkflowName: () => LocalizedString
			/**
			 * 无条件启动
			 */
			startUnconditional: () => LocalizedString
			/**
			 * 条件 %1 满足时就绪
			 */
			startCondition: () => LocalizedString
			/**
			 * 同时满足 %1 %2 %3 %4
			 */
			conditionAndMany: () => LocalizedString
			/**
			 * 任意满足 %1 %2 %3 %4
			 */
			conditionOrMany: () => LocalizedString
			/**
			 * 并且/或者积木至少需要连接两个条件
			 */
			twoConditionsRequired: () => LocalizedString
			/**
			 * 执行 %1
			 */
			execute: () => LocalizedString
			/**
			 * 识别到 %1 相似度 %2 匹配 %3 时就绪
			 */
			start: () => LocalizedString
			/**
			 * 等待图片 %1 相似度 %2 匹配 %3 超时 %4 毫秒
			 */
			waitImage: () => LocalizedString
			/**
			 * 等待图片 %1 %2 匹配 %3 超时 %4 毫秒
			 */
			waitImageState: () => LocalizedString
			/**
			 * 点击图片 %1 %2 %3 次 相似度 %4 匹配 %5 点击前确认 %6 最大移动 %7 像素
			 */
			clickImage: () => LocalizedString
			/**
			 * 移动到图片 %1 相似度 %2 匹配 %3
			 */
			moveToImage: () => LocalizedString
			/**
			 * 等待 %1 毫秒
			 */
			delay: () => LocalizedString
			/**
			 * 按键 %1
			 */
			keyPress: () => LocalizedString
			/**
			 * 组合键 Ctrl %1 Alt %2 Shift %3 Win %4 + %5
			 */
			keyCombo: () => LocalizedString
			/**
			 * 按住 %1 直到图片 %2 %3 匹配 %4 超时 %5 毫秒
			 */
			holdKeyUntilImage: () => LocalizedString
			/**
			 * 输入文本 %1 间隔 %2 毫秒
			 */
			textInput: () => LocalizedString
			/**
			 * 滚轮 横向 %1 纵向 %2
			 */
			scroll: () => LocalizedString
			/**
			 * 打开网址 %1
			 */
			navigate: () => LocalizedString
			/**
			 * 刷新当前页面
			 */
			reload: () => LocalizedString
			/**
			 * 记录日志 %1
			 */
			log: () => LocalizedString
			/**
			 * 如果 %1 图片 %2 相似度 %3 匹配 %4
			 */
			ifImage: () => LocalizedString
			/**
			 * 如果条件 %1
			 */
			ifCondition: () => LocalizedString
			/**
			 * 图片 %1 相似度 %2 匹配 %3
			 */
			imageCondition: () => LocalizedString
			/**
			 * %1 并且 %2
			 */
			conditionAnd: () => LocalizedString
			/**
			 * %1 或者 %2
			 */
			conditionOr: () => LocalizedString
			/**
			 * 不满足 %1
			 */
			conditionNot: () => LocalizedString
			/**
			 * 等待直到条件 %1 超时 %2 毫秒
			 */
			waitCondition: () => LocalizedString
			/**
			 * 那么 %1
			 */
			then: () => LocalizedString
			/**
			 * 否则 %1
			 */
			otherwise: () => LocalizedString
			/**
			 * 重复 %1 次
			 */
			repeat: () => LocalizedString
			/**
			 * 重复直到图片 %1 %2 匹配 %3 最多 %4 次
			 */
			repeatUntilImage: () => LocalizedString
			/**
			 * 重复直到条件 %1 最多 %2 次
			 */
			repeatUntilCondition: () => LocalizedString
			/**
			 * 出现
			 */
			visible: () => LocalizedString
			/**
			 * 消失
			 */
			hidden: () => LocalizedString
			/**
			 * 左键
			 */
			leftButton: () => LocalizedString
			/**
			 * 右键
			 */
			rightButton: () => LocalizedString
			/**
			 * 中键
			 */
			middleButton: () => LocalizedString
			/**
			 * 自动遮罩
			 */
			maskAuto: () => LocalizedString
			/**
			 * 透明遮罩
			 */
			maskAlpha: () => LocalizedString
			/**
			 * 完整图片
			 */
			maskFull: () => LocalizedString
			/**
			 * 识别到
			 */
			found: () => LocalizedString
			/**
			 * 未识别到
			 */
			notFound: () => LocalizedString
			/**
			 * 执行到这里
			 */
			logSample: () => LocalizedString
			/**
			 * 你好
			 */
			textSample: () => LocalizedString
			/**
			 * 入口
			 */
			catEntry: () => LocalizedString
			/**
			 * 图像
			 */
			catImage: () => LocalizedString
			/**
			 * 输入
			 */
			catInput: () => LocalizedString
			/**
			 * 页面
			 */
			catPage: () => LocalizedString
			/**
			 * 流程
			 */
			catFlow: () => LocalizedString
			/**
			 * 调试
			 */
			catDebug: () => LocalizedString
		}
		service: {
			state: {
				/**
				 * 出现
				 */
				visible: () => LocalizedString
				/**
				 * 消失
				 */
				hidden: () => LocalizedString
			}
			status: {
				/**
				 * 测试素材 {asset}
				 */
				checkingAsset: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 素材匹配成功，分数 {score}%
				 */
				assetMatch: (arg: { score: unknown }) => LocalizedString
				/**
				 * 未识别到素材 {asset}
				 */
				assetNoMatch: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 就绪检查失败：{detail}
				 */
				readyCheckFailed: (arg: { detail: unknown }) => LocalizedString
				/**
				 * 执行失败：{detail}
				 */
				runFailed: (arg: { detail: unknown }) => LocalizedString
				/**
				 * 素材测试已停止：{detail}
				 */
				assetTestStopped: (arg: { detail: unknown }) => LocalizedString
				/**
				 * 素材测试失败：{detail}
				 */
				assetTestFailed: (arg: { detail: unknown }) => LocalizedString
				/**
				 * 正在执行下一步
				 */
				stepNext: () => LocalizedString
				/**
				 * 脚本执行完成
				 */
				scriptCompleted: () => LocalizedString
				/**
				 * 脚本已停止
				 */
				scriptStopped: () => LocalizedString
				/**
				 * 识别到 {asset} · {score}% · {ms}ms
				 */
				imageMatch: (arg: { asset: unknown, ms: unknown, score: unknown }) => LocalizedString
				/**
				 * 已暂停，下一步：{step}
				 */
				pausedNext: (arg: { step: unknown }) => LocalizedString
			}
			step: {
				/**
				 * 执行流程
				 */
				sequence: () => LocalizedString
				/**
				 * 等待图片 {asset}
				 */
				waitImage: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 等待图片{state} {asset}
				 */
				waitImageState: (arg: { asset: unknown, state: unknown }) => LocalizedString
				/**
				 * 点击图片 {asset}
				 */
				clickImage: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 移动到图片 {asset}
				 */
				moveToImage: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 等待 {ms} 毫秒
				 */
				delay: (arg: { ms: unknown }) => LocalizedString
				/**
				 * 按键 {key}
				 */
				keyPress: (arg: { key: unknown }) => LocalizedString
				/**
				 * 按住 {key} 直到图片{state} {asset}
				 */
				keyHoldUntilImage: (arg: { asset: unknown, key: unknown, state: unknown }) => LocalizedString
				/**
				 * 输入文本
				 */
				textInput: () => LocalizedString
				/**
				 * 滚动页面
				 */
				scroll: () => LocalizedString
				/**
				 * 打开网页
				 */
				navigate: () => LocalizedString
				/**
				 * 刷新页面
				 */
				reload: () => LocalizedString
				/**
				 * 日志 {message}
				 */
				log: (arg: { message: unknown }) => LocalizedString
				/**
				 * 判断图片 {asset}
				 */
				ifImage: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 判断组合条件
				 */
				ifCondition: () => LocalizedString
				/**
				 * 等待组合条件
				 */
				waitCondition: () => LocalizedString
				/**
				 * 重复 {times} 次
				 */
				repeat: (arg: { times: unknown }) => LocalizedString
				/**
				 * 重复直到 {asset}
				 */
				repeatUntilImage: (arg: { asset: unknown }) => LocalizedString
				/**
				 * 重复直到组合条件
				 */
				repeatUntilCondition: () => LocalizedString
			}
		}
		ipc: {
			/**
			 * 打开自动化脚本包
			 */
			openPackageTitle: () => LocalizedString
			/**
			 * BaoFlash 自动化脚本
			 */
			openPackageFilter: () => LocalizedString
			/**
			 * 替换
			 */
			replace: () => LocalizedString
			/**
			 * 脚本已经存在
			 */
			packageExistsTitle: () => LocalizedString
			/**
			 * 脚本库中已有相同 ID 的脚本，是否使用导入文件替换？
			 */
			packageExistsMessage: () => LocalizedString
			/**
			 * 替换素材 {asset}
			 */
			replaceAssetTitle: (arg: { asset: unknown }) => LocalizedString
			/**
			 * 图片素材
			 */
			imageAssetFilter: () => LocalizedString
			/**
			 * 选择素材目录
			 */
			selectAssetDir: () => LocalizedString
			/**
			 * 导出自动化脚本包
			 */
			exportPackageTitle: () => LocalizedString
		}
	}
	error: {
		/**
		 * 出错了
		 */
		title: () => LocalizedString
		/**
		 * 组件渲染异常
		 */
		'default': () => LocalizedString
		/**
		 * DNS 解析失败
		 */
		dnsFail: () => LocalizedString
		/**
		 * 页面加载失败
		 */
		pageLoadFail: () => LocalizedString
		/**
		 * 页面崩溃了
		 */
		pageCrashed: () => LocalizedString
	}
}

export type Formatters = {}
